Repository godotengine/godot-cpp, pull requests merged in 2020-08, with the labels that each got.

#307 Fixed memory leak with String objects
  include/core/String.hpp
  src/core/String.cpp
Labels: enhancement

#415 Fix alloca.h error in Defs.h
  include/core/Defs.hpp
Labels: bug

#365 Fix `cast_to` for non-exposed engine types
  binding_generator.py
  include/core/Godot.hpp
Labels: bug

#416 Add option to generate template version of Node::get_node
  SConstruct
  binding_generator.py
Labels: enhancement

#371 Fix Vector's Bounce Reflect
  include/core/Vector2.hpp
  include/core/Vector3.hpp
Labels: bug

#382 Fix default value of `bits` misnaming resulting library
  SConstruct
Labels: bug, needs fixes

#450 Bugfix. Project generation now respects the given 'headers_dir' start…
  SConstruct
Labels: bug

#436 Additions to the library to support the ARCore plugin
  include/core/CameraMatrix.hpp
  include/core/RID.hpp
  src/core/CameraMatrix.cpp
  src/core/RID.cpp
Labels: enhancement
