Repository godotengine/godot-cpp, pull requests merged in 2021-03, with the labels that each got.

#456 Fix compiling using CMake and GCC
  CMakeLists.txt
Labels: bug, cmake

#507 Generate bindings if they are not found
  SConstruct
Labels: enhancement

#492 Search correct python interpeter in case missing default "python"
  CMakeLists.txt
Labels: bug, cmake

#517 Added freebsd specific configuration to SConstruct
  SConstruct
Labels: buildsystem, enhancement

#525 Update clang-format to version 11
  .clang-format
  .github/workflows/ci.yml
  include/core/AABB.hpp
  include/core/CameraMatrix.hpp
  include/core/Color.hpp
  include/core/Godot.hpp
  include/core/GodotGlobal.hpp
  include/core/Math.hpp
  include/core/PoolArrays.hpp
  include/core/Rect2.hpp
  include/core/Ref.hpp
  include/core/String.hpp
  include/core/Vector3.hpp
  misc/ci/sources.list
  src/core/AABB.cpp
  src/core/Basis.cpp
  src/core/CameraMatrix.cpp
  src/core/Color.cpp
  src/core/GodotGlobal.cpp
  src/core/Plane.cpp
  src/core/Quat.cpp
  src/core/Rect2.cpp
  src/core/String.cpp
  src/core/TagDB.cpp
  src/core/Transform.cpp
  src/core/Transform2D.cpp
Labels: buildsystem, enhancement

#400 Fixed cmake source file generation
  CMakeLists.txt
  binding_generator.py
Labels: cmake, enhancement

#530 Add JavaScript platform support (emcc, wasm).
  README.md
  SConstruct
Labels: buildsystem, documentation, enhancement, platform:html5
