Repository godotengine/godot-cpp, pull requests merged in 2021-09, with the labels that each got.

#608 Fix typo in README.md
  README.md
Labels: bug

#594 Remove extraneous Error enum values that were removed in Godot 3.0
  include/core/Defs.hpp
Labels: bug

#590 Fix binding when default parameter is a PoolByteArray.
  binding_generator.py
Labels: bug

#616 Escape parameters named `enum`.
  binding_generator.py
Labels: bug

#617 CI: Update Linux runner to Ubuntu 18.04
  .github/workflows/ci.yml
Labels: bug, platform:linuxbsd, buildsystem

#618 CI: Run tests with Godot 3.3.3
  .github/workflows/ci.yml
Labels: enhancement, buildsystem

#587 Fix OSX library name for arm64.
  SConstruct
Labels: bug

#607 Fix clang 11 build failure over Wabsolute-value
  src/core/CameraMatrix.cpp
Labels: bug

#595 Add license headers to all source and header files
  include/core/AABB.hpp
  include/core/Array.hpp
  include/core/Basis.hpp
  include/core/CameraMatrix.hpp
  include/core/Color.hpp
  include/core/CoreTypes.hpp
  include/core/Defs.hpp
  include/core/Dictionary.hpp
  include/core/Godot.hpp
  include/core/GodotGlobal.hpp
  include/core/GodotProfiling.hpp
  include/core/Math.hpp
  include/core/NodePath.hpp
  include/core/Plane.hpp
  include/core/PoolArrays.hpp
  include/core/Quat.hpp
  include/core/RID.hpp
  include/core/Rect2.hpp
  include/core/Ref.hpp
  include/core/String.hpp
  include/core/TagDB.hpp
  include/core/Transform.hpp
  include/core/Transform2D.hpp
  include/core/Variant.hpp
  include/core/Vector2.hpp
  include/core/Vector3.hpp
  include/core/Wrapped.hpp
  src/core/AABB.cpp
  src/core/Array.cpp
  src/core/Basis.cpp
  src/core/CameraMatrix.cpp
  src/core/Color.cpp
  src/core/Dictionary.cpp
  src/core/GodotGlobal.cpp
  src/core/NodePath.cpp
  src/core/Plane.cpp
  src/core/PoolArrays.cpp
  src/core/Quat.cpp
  src/core/RID.cpp
  src/core/Rect2.cpp
  src/core/String.cpp
  src/core/TagDB.cpp
  src/core/Transform.cpp
  src/core/Transform2D.cpp
  src/core/Variant.cpp
  src/core/Vector2.cpp
  src/core/Vector3.cpp
  test/src/init.cpp
Labels: enhancement

#601 Fix argument constness in String::begins_with, String::ends_with
  include/core/String.hpp
  src/core/String.cpp
Labels: bug

#588 Add ability to easily register signals with no arguments
  include/core/Godot.hpp
Labels: enhancement

#563 Stop including iostream in Variant.hpp (to produce slightly smaller binaries)
  include/core/Godot.hpp
  include/core/Variant.hpp
  src/core/Variant.cpp
Labels: enhancement

#547 Fix: add missing toolchain elements for android
  SConstruct
Labels: enhancement, platform:android, buildsystem

#538 Update godot version in README.MD
  README.md
Labels: enhancement, documentation

#513 Add -std:c++17 flag on windows test build
  test/SConstruct
Labels: enhancement, platform:windows, buildsystem

#619 Updating the readme with new branch info
  README.md
Labels: enhancement, documentation

#620 bindgen: Properly escape NodePath in default args
  binding_generator.py
Labels: bug, buildsystem

#622 CI: Disable test build to prepare for 4.0 extensions merge
  .github/workflows/ci.yml
Labels: enhancement, buildsystem, gdextension

#626 Use default destructor for Object
  binding_generator.py
Labels: enhancement

#625 Add pointers support for virtual methods.
  include/godot_cpp/core/method_ptrcall.hpp
Labels: enhancement, gdextension

#631 Add Ref<T> binding support.
  include/godot_cpp/classes/ref.hpp
  test/demo/main.gd
  test/src/example.cpp
  test/src/example.h
Labels: bug, discussion, gdextension

#632 test: Setup for building both debug and release build
  test/SConstruct
  test/demo/example.gdextension
Labels: enhancement, gdextension
