Repository godotengine/godot-cpp, pull requests merged in 2021-12, with the labels that each got.

#665 CI: Update Godot binary to 3.4-stable for tests
  .github/workflows/ci.yml
Labels: buildsystem, cherrypick:3.4

#666 Call Variant destructor in operator= to prevent a memory leak
  src/core/Variant.cpp
Labels: bug, cherrypick:3.4

#670 Require at least Python 3
  CMakeLists.txt
Labels: bug, cherrypick:3.x, cherrypick:3.4, cherrypick:3.3

#671 Fix namespace to be consistent with the previous ADD functions
  include/godot_cpp/core/object.hpp
Labels: bug

#672 Explicit namespace for macros
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/core/object.hpp
Labels: enhancement

#518 Test CMake project with CI
  .github/workflows/ci.yml
  CMakeLists.txt
  test/CMakeLists.txt
Labels: enhancement, buildsystem
