Repository godotengine/godot-cpp, pull requests merged in 2021-11, with the labels that each got.

#646 Add `Array::make` macro
  binding_generator.py
  include/godot_cpp/variant/array_helpers.hpp
Labels: enhancement

#649 Synced windows compile definitions with scons configuration
  CMakeLists.txt
Labels: platform:windows, cmake, buildsystem

#627 Implement index operators for Arrays
  binding_generator.py
  src/variant/packed_arrays.cpp
  test/demo/main.gd
  test/src/example.cpp
  test/src/example.h
Labels: enhancement, gdextension

#661 Print a warning with unknown SCons variables to ease troubleshooting
  SConstruct
Labels: enhancement, cherrypick:3.x, cherrypick:3.4

#659 Avoid crash in Variant constructor from nullptr Object*
  src/variant/variant.cpp
Labels: bug, crash
