Repository godotengine/godot-cpp, pull requests merged in 2021-02, with the labels that each got.

#504 Replaced static math functions in CameraMatrix by Math usage
  include/core/CameraMatrix.hpp
  src/core/CameraMatrix.cpp
Labels: enhancement

#506 Fix MacOS CI using an available runner
  .github/workflows/ci.yml
Labels: bug

#501 Dont carry MSVC stuff to MinGW builds
  SConstruct
Labels: bug, platform:android, platform:windows

#502 Re-added clang-format checks to the CI
  .github/workflows/ci.yml
  include/core/CameraMatrix.hpp
  include/core/GodotProfiling.hpp
  misc/scripts/clang_format.sh
  misc/travis/clang-format.sh
Labels: enhancement

#505 iOS arm64 simulator support.
  SConstruct
Labels: enhancement

#477 Test built GDNative plugin with stable Godot
  .github/workflows/ci.yml
  test/SConstruct
  test/gdexample.gdnlib
  test/gdexample.gdns
  test/project.godot
  test/script.gd
  test/src/init.cpp
Labels: enhancement
