Repository godotengine/godot-cpp, pull requests merged in 2022-05, with the labels that each got.

#749 [CI] Add python file format to static checks.
  .github/workflows/ci.yml
  SConstruct
  binding_generator.py
Labels: enhancement, buildsystem

#748 [Scons] Use dependency to track bindings generation.
  SConstruct
  binding_generator.py
Labels: enhancement, buildsystem

#746 Build javascript target on windows host
  SConstruct
Labels: bug, platform:windows, platform:html5

#757 Cast `GetTypeInfo::VARIANT_TYPE` to `GDNativeVariantType`
  include/godot_cpp/core/binder_common.hpp
  include/godot_cpp/core/method_bind.hpp
Labels: bug
