Repository godotengine/godot-cpp, pull requests merged in 2022-11, with the labels that each got.

#908 [SCons] Remove bogus CCFLAGS from windows toolchain.
  tools/windows.py
Labels: bug, platform:windows, buildsystem

#913 Fix Android build on macOS.
  test/demo/example.gdextension
  tools/android.py
Labels: bug, platform:android, buildsystem

#920 Fix namespace isolation in GDCLASS macro
  include/godot_cpp/classes/wrapped.hpp
Labels: bug

#924 Update named colors to be in sync with the engine
  include/godot_cpp/variant/color_names.inc.hpp
Labels: bug

#929 Basic static analysis fixes
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/memory.hpp
  include/godot_cpp/core/method_bind.hpp
  include/godot_cpp/godot.hpp
  include/godot_cpp/templates/cowdata.hpp
  include/godot_cpp/templates/hashfuncs.hpp
  include/godot_cpp/templates/rb_set.hpp
  include/godot_cpp/templates/rid_owner.hpp
  include/godot_cpp/variant/basis.hpp
  include/godot_cpp/variant/plane.hpp
  include/godot_cpp/variant/quaternion.hpp
  src/variant/basis.cpp
  src/variant/projection.cpp
Labels: bug

#932 [SCons] Link MSVC debug runtime for optimize=none|debug only.
  tools/targets.py
  tools/windows.py
Labels: bug, needs testing, platform:windows, buildsystem

#930 Add missing String operators
  binding_generator.py
  src/variant/char_string.cpp
Labels: bug

#927 Fix some type warnings in example
  test/src/example.cpp
Labels: bug
