Repository godotengine/godot-cpp, pull requests merged in 2022-12, with the labels that each got.

#897 Fix const qualifier for parameters in GDExtension api functions
  README.md
  binding_generator.py
  godot-headers/godot/gdnative_interface.h
  include/godot_cpp/classes/ref.hpp
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/binder_common.hpp
  include/godot_cpp/core/builtin_ptrcall.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/core/engine_ptrcall.hpp
  include/godot_cpp/core/method_bind.hpp
  include/godot_cpp/core/method_ptrcall.hpp
  include/godot_cpp/core/type_info.hpp
  include/godot_cpp/godot.hpp
  include/godot_cpp/variant/variant.hpp
  src/classes/wrapped.cpp
  src/core/class_db.cpp
  src/core/method_bind.cpp
  src/godot.cpp
  src/variant/variant.cpp
  test/src/register_types.cpp
Labels: bug, gdextension

#947 {cmake} Updates for target-based approach
  CMakeLists.txt
Labels: enhancement, buildsystem

#948 Fix cast on PtrToArg::convert
  include/godot_cpp/core/method_ptrcall.hpp
Labels: bug

#949 Change example code to properly test refcounted objects
  test/demo/main.gd
  test/demo/main.tscn
  test/src/example.cpp
  test/src/example.h
Labels: enhancement

#959 Use `int64_t` for `BitField` as in Godot itself
  include/godot_cpp/core/type_info.hpp
Labels: gdextension

#958 Fix virtual GDExtension method Ref<T> conversion
  godot-headers/godot/gdextension_interface.h
  include/godot_cpp/classes/ref.hpp
Labels: enhancement

#962 Extension header: amend const correctness of `p_args` parameters
  gdextension/gdextension_interface.h
  include/godot_cpp/core/binder_common.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/core/method_bind.hpp
  src/core/method_bind.cpp
Labels: bug

#903 Make build_library=no usable at godot-cpp's root
  .github/workflows/ci.yml
  binding_generator.py
Labels: bug, buildsystem

#961 Fix incorrect length passed to `CharString`
  src/variant/char_string.cpp
Labels: bug

#971 [SCons] Platform agnostic default toolchain (GNU).
  SConstruct
  tools/windows.py
Labels: enhancement, buildsystem

#974 Add .gdignore file to godot-cpp, for use as submodule in Godot projects
  .gdignore
Labels: enhancement, cherrypick:3.x, cherrypick:3.5
