Repository godotengine/godot-cpp, pull requests merged in 2022-06, with the labels that each got.

#759 Unify bits, android_arch, macos_arch ios_arch into arch, support non-x86 Linux
  .github/workflows/ci.yml
  README.md
  SConstruct
  binding_generator.py
  test/demo/example.gdextension
  test/demo/icon.png.import
  test/demo/main.gd
  test/demo/main.tscn
  test/demo/project.godot
Labels: enhancement, buildsystem

#691 [3.x] Scons boilerplate for building projects. Android, iOS builds.
  .github/workflows/ci.yml
  SConstruct
  test/SConstruct
  test/gdexample.gdnlib
Labels: enhancement, buildsystem

#766 [SCons] Fix Android builds with modern NDKs.
  SConstruct
Labels: bug, platform:android, buildsystem, gdextension, cherrypick:3.4

#770 [3.4] [SCons] Fix Android builds with modern NDKs.
  SConstruct
Labels: bug, platform:android, buildsystem

#776 Fix Rect2::distance_to not returning 0
  src/core/Rect2.cpp
Labels: bug

#762 [SCons] Move toolchains logic to tools folder, various improvements.
  SConstruct
  test/demo/example.gdextension
  tools/android.py
  tools/ios.py
  tools/ios_osxcross.py
  tools/javascript.py
  tools/linux.py
  tools/my_spawn.py
  tools/osx.py
  tools/osxcross.py
  tools/windows.py
Labels: usability, buildsystem
