Repository godotengine/godot-cpp, pull requests merged in 2022-10, with the labels that each got.

#867 [SCons] Unify tools/target build type configuration
  .github/workflows/ci.yml
  .gitignore
  SConstruct
  test/SConstruct
  test/demo/bin/libgdexample.osx.template_debug.framework/Resources/Info.plist
  test/demo/bin/libgdexample.osx.template_release.framework/Resources/Info.plist
  test/demo/example.gdextension
  tools/targets.py
Labels: enhancement, waiting for Godot, needs testing, buildsystem

#857 Update Vector2/2i/3/3i/4/4i to match the engine
  include/godot_cpp/variant/vector2.hpp
  include/godot_cpp/variant/vector2i.hpp
  include/godot_cpp/variant/vector3.hpp
  include/godot_cpp/variant/vector3i.hpp
  include/godot_cpp/variant/vector4.hpp
  include/godot_cpp/variant/vector4i.hpp
  src/variant/vector2.cpp
  src/variant/vector3.cpp
  src/variant/vector3i.cpp
  src/variant/vector4.cpp
  src/variant/vector4i.cpp
Labels: enhancement

#859 Update Basis/Transform3D/Quaternion to match the engine
  include/godot_cpp/core/math.hpp
  include/godot_cpp/variant/basis.hpp
  include/godot_cpp/variant/quaternion.hpp
  include/godot_cpp/variant/transform3d.hpp
  src/variant/basis.cpp
  src/variant/quaternion.cpp
  src/variant/transform3d.cpp
Labels: enhancement

#855 Fix deriving a custom class with virtual methods
  binding_generator.py
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/class_db.hpp
  src/core/class_db.cpp
Labels: bug, gdextension

#864 Fix passing null to functions taking Object parameters
  binding_generator.py
Labels: bug

#880 Use `struct` instead of `class` for core structures
  binding_generator.py
  include/godot_cpp/core/defs.hpp
  include/godot_cpp/variant/aabb.hpp
  include/godot_cpp/variant/basis.hpp
  include/godot_cpp/variant/color.hpp
  include/godot_cpp/variant/plane.hpp
  include/godot_cpp/variant/projection.hpp
  include/godot_cpp/variant/quaternion.hpp
  include/godot_cpp/variant/rect2.hpp
  include/godot_cpp/variant/rect2i.hpp
  include/godot_cpp/variant/transform2d.hpp
  include/godot_cpp/variant/transform3d.hpp
  include/godot_cpp/variant/vector2.hpp
  include/godot_cpp/variant/vector2i.hpp
  include/godot_cpp/variant/vector3.hpp
  include/godot_cpp/variant/vector3i.hpp
  include/godot_cpp/variant/vector4.hpp
  include/godot_cpp/variant/vector4i.hpp
  src/variant/variant.cpp
Labels: enhancement, breaks compat

#876 Add detail infos for binding error message.
  include/godot_cpp/core/class_db.hpp
  src/core/class_db.cpp
Labels: enhancement

#881 Bind enums in built-in types and expose bindings for global constants
  binding_generator.py
  include/godot_cpp/core/binder_common.hpp
Labels: bug, gdextension

#884 Update Makefile after recent buildsystem changes
  Makefile
Labels: bug, buildsystem

#885 Update core data structures to match the engine
  include/godot_cpp/core/math.hpp
  include/godot_cpp/variant/aabb.hpp
  include/godot_cpp/variant/basis.hpp
  include/godot_cpp/variant/color.hpp
  include/godot_cpp/variant/plane.hpp
  include/godot_cpp/variant/projection.hpp
  include/godot_cpp/variant/quaternion.hpp
  include/godot_cpp/variant/rect2.hpp
  include/godot_cpp/variant/rect2i.hpp
  include/godot_cpp/variant/transform2d.hpp
  include/godot_cpp/variant/vector4i.hpp
  src/variant/aabb.cpp
  src/variant/basis.cpp
  src/variant/color.cpp
  src/variant/plane.cpp
  src/variant/projection.cpp
  src/variant/quaternion.cpp
  src/variant/rect2.cpp
  src/variant/rect2i.cpp
  src/variant/transform2d.cpp
  src/variant/vector4i.cpp
Labels: enhancement

#887 Add more static checks and move to separate file to match main repo
  .clang-format
  .github/workflows/ci.yml
  .github/workflows/static_checks.yml
  include/godot_cpp/classes/ref.hpp
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/binder_common.hpp
  include/godot_cpp/core/builtin_ptrcall.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/core/defs.hpp
  include/godot_cpp/core/engine_ptrcall.hpp
  include/godot_cpp/core/error_macros.hpp
  include/godot_cpp/core/memory.hpp
  include/godot_cpp/core/method_bind.hpp
  include/godot_cpp/core/method_ptrcall.hpp
  include/godot_cpp/core/mutex_lock.hpp
  include/godot_cpp/core/object.hpp
  include/godot_cpp/core/property_info.hpp
  include/godot_cpp/core/type_info.hpp
  include/godot_cpp/godot.hpp
  include/godot_cpp/templates/cowdata.hpp
  include/godot_cpp/templates/hash_map.hpp
  include/godot_cpp/templates/hash_set.hpp
  include/godot_cpp/templates/hashfuncs.hpp
  include/godot_cpp/templates/list.hpp
  include/godot_cpp/templates/pair.hpp
  include/godot_cpp/templates/rb_map.hpp
  include/godot_cpp/templates/rb_set.hpp
  include/godot_cpp/templates/rid_owner.hpp
  include/godot_cpp/templates/safe_refcount.hpp
  include/godot_cpp/templates/search_array.hpp
  include/godot_cpp/templates/self_list.hpp
  include/godot_cpp/templates/sort_array.hpp
  include/godot_cpp/templates/spin_lock.hpp
  include/godot_cpp/templates/thread_work_pool.hpp
  include/godot_cpp/templates/vector.hpp
  include/godot_cpp/templates/vmap.hpp
  include/godot_cpp/templates/vset.hpp
  include/godot_cpp/variant/char_string.hpp
  include/godot_cpp/variant/char_utils.hpp
  include/godot_cpp/variant/typed_array.hpp
  include/godot_cpp/variant/ucaps.hpp
  include/godot_cpp/variant/variant.hpp
  misc/scripts/clang_format.sh
  misc/scripts/file_format.sh
  misc/scripts/header_guards.sh
  misc/scripts/mypy.ini
  misc/scripts/mypy_check.sh
  test/demo/main.gd
Labels: enhancement, buildsystem

#891 Fix use-after-free when deleting objects from extension terminator
  src/godot.cpp
Labels: bug, gdextension

#888 Use enum type in GDExtension info structs for better readability
  godot-headers/godot/gdnative_interface.h
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/method_bind.hpp
  src/core/class_db.cpp
Labels: enhancement, gdextension

#883 Add support for virtual and abstract classes
  godot-headers/godot/gdnative_interface.h
  include/godot_cpp/core/class_db.hpp
  test/src/example.h
  test/src/register_types.cpp
Labels: enhancement, gdextension

#895 Add missing bindings for GDNativePtr<void>.
  include/godot_cpp/core/method_ptrcall.hpp
Labels: bug, gdextension
