Repository godotengine/godot-cpp, pull requests merged in 2022-02, with the labels that each got.

#636 Android/iOS build, Scons boilerplate for building projects.
  .github/workflows/ci.yml
  SConstruct
  test/SConstruct
Labels: enhancement, platform:android, platform:ios, buildsystem, gdextension

#690 [Build] Fix exposed suffix, remove unused option.
  SConstruct
Labels: bug, buildsystem

#696 [macOS] Restore demo library output names.
  SConstruct
  test/SConstruct
  test/demo/bin/libgdexample.osx.debug.framework/Resources/Info.plist
  test/demo/bin/libgdexample.osx.release.framework/Resources/Info.plist
  test/demo/example.gdextension
Labels: enhancement, platform:ios, platform:macos, gdextension

#695 Add `ptr()` / `ptrw()` to the arrays, add missing `String` methods, add missing `CharString` method implementations.
  binding_generator.py
  include/godot_cpp/variant/aabb.hpp
  include/godot_cpp/variant/basis.hpp
  include/godot_cpp/variant/char_string.hpp
  include/godot_cpp/variant/color.hpp
  include/godot_cpp/variant/plane.hpp
  include/godot_cpp/variant/quaternion.hpp
  include/godot_cpp/variant/rect2.hpp
  include/godot_cpp/variant/rect2i.hpp
  include/godot_cpp/variant/transform2d.hpp
  include/godot_cpp/variant/transform3d.hpp
  include/godot_cpp/variant/variant.hpp
  include/godot_cpp/variant/vector2.hpp
  include/godot_cpp/variant/vector2i.hpp
  include/godot_cpp/variant/vector3.hpp
  include/godot_cpp/variant/vector3i.hpp
  src/core/method_bind.cpp
  src/variant/char_string.cpp
  src/variant/packed_arrays.cpp
  src/variant/variant.cpp
Labels: enhancement, gdextension

#699 Add Variant binders for the generated classes, structs and global enums
  binding_generator.py
Labels: bug, enhancement, gdextension

#704 Fix "const" NativePtr binds.
  binding_generator.py
  include/godot_cpp/core/method_ptrcall.hpp
Labels: bug, gdextension

#705 Use C++17 flag only for C++ files.
  SConstruct
Labels: bug, enhancement, gdextension

#706 Add ERR_ macros variants using `String` messages.
  include/godot_cpp/core/error_macros.hpp
  src/core/error_macros.cpp
Labels: enhancement, gdextension

#688 Add missing Vector3::operator Vector3i definition
  include/godot_cpp/variant/vector2.hpp
  src/variant/vector2.cpp
  src/variant/vector3.cpp
Labels: bug

#707 Use forward declares for vector math types
  include/godot_cpp/variant/rect2.hpp
  include/godot_cpp/variant/rect2i.hpp
  include/godot_cpp/variant/vector2.hpp
  include/godot_cpp/variant/vector2i.hpp
  include/godot_cpp/variant/vector3.hpp
  include/godot_cpp/variant/vector3i.hpp
  src/variant/rect2.cpp
  src/variant/rect2i.cpp
  src/variant/vector2.cpp
  src/variant/vector2i.cpp
  src/variant/vector3.cpp
  src/variant/vector3i.cpp
Labels: enhancement, gdextension

#683 Fix Test CMake project for Windows and parametrize paths
  .github/workflows/ci.yml
  CMakeLists.txt
  test/.gitignore
  test/CMakeLists.txt
Labels: bug

#708 Fix GDCLASS when inherited class is in another namespace
  include/godot_cpp/classes/wrapped.hpp
Labels: bug, gdextension

#710 [3.x] Run black format on SConstruct files and bindings generator
  SConstruct
  binding_generator.py
  test/SConstruct
Labels: enhancement, buildsystem

#712 [master] Run black format on SConstruct files and bindings generator
  SConstruct
  binding_generator.py
  test/SConstruct
Labels: enhancement, buildsystem

#711 [3.4] Run black format on SConstruct files and bindings generator
  SConstruct
  binding_generator.py
  test/SConstruct
Labels: enhancement, buildsystem
