Repository godotengine/godot-cpp, pull requests merged in 2022-09, with the labels that each got.

#822 Fix Basis constructor: row vectors -> column vectors
  include/godot_cpp/variant/basis.hpp
Labels: bug

#823 Ensure GDCLASS can be used outside the godot namespace.
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/error_macros.hpp
  include/godot_cpp/core/memory.hpp
Labels: bug, gdextension

#828 Generate constants in the bindings generator
  binding_generator.py
Labels: bug

#817 Relicense integration testing project under public domain/Unlicense
  misc/scripts/clang_format.sh
  test/README.md
  test/src/example.cpp
  test/src/example.h
  test/src/register_types.cpp
  test/src/register_types.h
Labels: enhancement, gdextension

#832 Upgrade 3.x CI to Godot 3.5-stable
  .github/workflows/ci.yml
  .gitignore
Labels: enhancement, cherrypick:3.5

#833 Add Godot 3.x ignores to the .gitignore file in master
  .github/workflows/ci.yml
  .gitignore
Labels: enhancement

#836 Fix get_file_list not returning all generated files.
  .github/workflows/ci.yml
  binding_generator.py
  misc/scripts/check_get_file_list.py
Labels: bug, buildsystem, gdextension

#819 Update hashfuncs, add some missing math funcs.
  CMakeLists.txt
  include/godot_cpp/core/math.hpp
  include/godot_cpp/templates/hashfuncs.hpp
  test/CMakeLists.txt
  test/src/register_types.cpp
  test/src/tests.h
  tools/windows.py
Labels: bug, gdextension

#839 Add SelfList template
  include/godot_cpp/templates/self_list.hpp
  test/src/tests.h
Labels: enhancement

#840 Move some methods to Animation from Variant
  godot-headers/godot/gdnative_interface.h
  src/variant/variant.cpp
Labels: enhancement, gdextension

#826 Change PropertyInfo members to String.
  include/godot_cpp/classes/ref.hpp
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/core/method_bind.hpp
  include/godot_cpp/core/property_info.hpp
  include/godot_cpp/core/type_info.hpp
  src/core/class_db.cpp
  test/src/example.cpp
  test/src/example.h
Labels: enhancement, gdextension

#844 Fix issues with `_get` and `_get_property_list`
  include/godot_cpp/classes/wrapped.hpp
Labels: bug, gdextension

#852 Update math functions with recent changes and additions from Godot
  include/godot_cpp/core/math.hpp
  src/variant/basis.cpp
  src/variant/quaternion.cpp
Labels: enhancement

#835 [SCons] Add "optimize" and "debug_symbols" options.
  .github/workflows/ci.yml
  SConstruct
  tools/android.py
  tools/ios.py
  tools/linux.py
  tools/macos.py
  tools/targets.py
  tools/windows.py
Labels: enhancement, buildsystem, gdextension

#853 [CI] Add concurrency and scons caching.
  .github/actions/godot-cache/action.yml
  .github/workflows/ci.yml
Labels: enhancement, buildsystem

#856 Rename Transform2D and Basis `elements` to `columns` and `rows` respectively
  include/godot_cpp/variant/basis.hpp
  include/godot_cpp/variant/transform2d.hpp
  include/godot_cpp/variant/transform3d.hpp
  src/variant/basis.cpp
  src/variant/projection.cpp
  src/variant/rect2.cpp
  src/variant/transform2d.cpp
Labels: enhancement
