Repository godotengine/godot-cpp, pull requests merged in 2022-03, with the labels that each got.

#715 Reorder native extension initialization steps
  include/godot_cpp/godot.hpp
  src/godot.cpp
Labels: bug

#719 Fixed crash on release builds due to missing argument type information
  include/godot_cpp/core/method_bind.hpp
Labels: bug, crash

#723 CI: Install MinGW via `egor-tensin/setup-mingw`
  .github/workflows/ci.yml
Labels: bug, buildsystem, cherrypick:3.x, cherrypick:3.4

#721 Fix return type encoding for ptrcall.
  binding_generator.py
Labels: bug, crash, gdextension

#724 Fix build after "Discern between VIRTUAL and ABSTRACT class bindings".
  godot-headers/godot/gdnative_interface.h
  include/godot_cpp/core/class_db.hpp
Labels: gdextension

#730 Fix generating static methods without return value.
  binding_generator.py
Labels: bug, gdextension
