Repository godotengine/godot-cpp, pull requests merged in 2022-01, with the labels that each got.

#668 Fix object_set_instance being wrongly called for built-in wrapped classes
  include/godot_cpp/classes/wrapped.hpp
  src/classes/wrapped.cpp
Labels: bug, gdextension

#682 [Demo Project] Add macOS framework config.
  test/SConstruct
  test/demo/bin/libgdexample.debug.framework/Resources/Info.plist
  test/demo/bin/libgdexample.release.framework/Resources/Info.plist
  test/demo/example.gdextension
  test/demo/main.tscn
Labels: enhancement, platform:macos, buildsystem

#676 [3.x] In CMakeLists, use the new FindPython3 instead of FindPython
  CMakeLists.txt
Labels: enhancement

#685 Update README file for macos support
  README.md
Labels: enhancement
