Repository godotengine/godot-cpp, pull requests merged in 2022-07, with the labels that each got.

#778 Fix crash when using static methods without return value due to uninitialized GDNativePropertyInfo struct members
  include/godot_cpp/core/method_bind.hpp
Labels: bug

#781 [SCons] Fix msvc, linux-clang, add version check.
  .github/workflows/ci.yml
  SConstruct
  tools/linux.py
  tools/windows.py
Labels: bug, buildsystem, gdextension

#782 Add clang-cl support
  tools/windows.py
Labels: enhancement, platform:windows, gdextension

#774 Update register initializer/terminator in README
  README.md
Labels: enhancement

#788 SCons: Default `num_jobs` to max CPUs minus 1 if not specified
  .github/workflows/ci.yml
  SConstruct
Labels: enhancement, buildsystem, cherrypick:3.x

#667 Generate binary in the current CMake source dir
  CMakeLists.txt
Labels: enhancement

#732 Fix compile fail when windows with llvm+ninja
  CMakeLists.txt
Labels: bug, platform:windows, cmake, cherrypick:3.x

#687 Fix default library filename generation in CMakeLists.txt
  CMakeLists.txt
Labels: bug, cherrypick:3.x

#794 Object::cast_to checks provided object for nullptr
  include/godot_cpp/core/object.hpp
Labels: bug

#797 [CI] Fix Android builds after GH container update.
  .github/workflows/ci.yml
  tools/android.py
Labels: bug, buildsystem

#677 Fixed pointer indirection in the PtrToArg template for Object arguments.
  include/godot_cpp/classes/ref.hpp
  include/godot_cpp/core/method_ptrcall.hpp
Labels: bug, gdextension

#798 Fix "_instance_bindings != nullptr" for Wrapped objects.
  include/godot_cpp/classes/wrapped.hpp
Labels: bug, gdextension

#796 Add debug information to Windows builds
  tools/windows.py
Labels: enhancement, platform:windows, gdextension

#799 Allow GDCLASS in own namespaces
  include/godot_cpp/classes/wrapped.hpp
Labels: bug
