Repository godotengine/godot-cpp, pull requests merged in 2023-09, with the labels that each got.

#1091 Implement vararg methods of builtin classes.
  binding_generator.py
  include/godot_cpp/variant/variant.hpp
Labels: enhancement, topic:gdextension

#1227 Cherry-picks for the godot-cpp 4.1 branch - 2nd batch
  README.md
  SConstruct
  binding_generator.py
  include/godot_cpp/templates/cowdata.hpp
  include/godot_cpp/variant/vector3.hpp
  include/godot_cpp/variant/vector3i.hpp
  include/godot_cpp/variant/vector4.hpp
  include/godot_cpp/variant/vector4i.hpp
  test/project/example.gdextension
  test/project/main.gd
  test/project/project.godot
  test/src/example.cpp
  test/src/example.h
  tools/godotcpp.py
  tools/targets.py
Labels: bug, enhancement

#1228 GDExtension: fix `bool` unknown in C
  gdextension/gdextension_interface.h
  include/godot_cpp/classes/wrapped.hpp
Labels: bug, topic:gdextension

#1233 Ensure `const` correctness for wrappers
  include/godot_cpp/classes/wrapped.hpp
Labels: bug, cherrypick:4.0, cherrypick:4.1

#1214 Ensure that PtrToArg specializations for native structs are used
  binding_generator.py
  include/godot_cpp/core/method_ptrcall.hpp
Labels: bug, cherrypick:4.1

#1237 [SCons] Fixed crashes in several scripts
  SConstruct
  tools/android.py
  tools/godotcpp.py
  tools/javascript.py
  tools/macos.py
Labels: bug, cherrypick:4.1

#970 Implement register unexposed classes
  gdextension/gdextension_interface.h
  include/godot_cpp/core/class_db.hpp
Labels: enhancement, topic:gdextension

#1239 Support `_validate_property()`
  gdextension/gdextension_interface.h
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/core/property_info.hpp
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
Labels: enhancement

#1243 Load 'print_error_with_message' function
  src/godot.cpp
Labels: bug, crash, regression, topic:gdextension, cherrypick:4.1

#1164 Add static methods to `ClassDB` for the methods bound to the `ClassDB` singleton
  binding_generator.py
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/class_db.hpp
Labels: enhancement, cherrypick:4.1

#1245 Fix allocation size overflow check in `CowData`
  include/godot_cpp/templates/cowdata.hpp
Labels: bug, crash, cherrypick:4.1

#1246 Update for addition of `get_virtual_call_data_func` and `call_virtual_func` to `GDExtensionClassCreationInfo2`
  gdextension/gdextension_interface.h
  include/godot_cpp/core/class_db.hpp
Labels: bug

#1244 Cherry-picks for the godot-cpp 4.1 branch - 3rd batch
  .github/workflows/ci.yml
  .github/workflows/static_checks.yml
  SConstruct
  binding_generator.py
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/core/method_ptrcall.hpp
  src/godot.cpp
  test/project/project.godot
  tools/android.py
  tools/godotcpp.py
  tools/javascript.py
  tools/macos.py
Labels: bug, enhancement

#1220 Add support to import custom variables from parent SConstruct (redux)
  SConstruct
Labels: enhancement, topic:buildsystem, cherrypick:4.1

#1165 Handle missing instance binding callbacks by finding the closest parent
  src/core/class_db.cpp
Labels: bug, cherrypick:4.1

#1155 Implement `callable_mp()` and `callable_mp_static()`
  gdextension/gdextension_interface.h
  include/godot_cpp/core/binder_common.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/godot.hpp
  include/godot_cpp/variant/callable_method_pointer.hpp
  src/godot.cpp
  src/variant/callable_method_pointer.cpp
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
Labels: enhancement

#1200 Changes necessary for hot reload to work
  gdextension/gdextension_interface.h
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/class_db.hpp
  src/classes/wrapped.cpp
  src/core/class_db.cpp
  tools/godotcpp.py
  tools/linux.py
Labels: enhancement

#1254 [3.x] CI: Update all images and actions
  .github/workflows/ci.yml
Labels: enhancement, topic:buildsystem, cherrypick:3.5
