Repository godotengine/godot-cpp, pull requests merged in 2023-10, with the labels that each got.

#1247 Javascript Web WASM Fix
  .github/workflows/ci.yml
  test/project/example.gdextension
  tools/javascript.py
Labels: bug, platform:web, topic:buildsystem, topic:gdextension, cherrypick:4.1

#1257 Update for `get_class_category` added to `GDExtensionScriptInstanceInfo2`
  gdextension/gdextension_interface.h
Labels: documentation

#1264 Miscellaneous updates to gdextension_interface.h
  gdextension/gdextension_interface.h
Labels: enhancement, topic:gdextension

#1265 Declare explicit specializations for `CharStringT`
  include/godot_cpp/variant/char_string.hpp
Labels: bug, cherrypick:4.1

#1263 Use the new `string_name_new_with_latin1_chars` function to improve StringName construction performance
  binding_generator.py
  gdextension/gdextension_interface.h
  include/godot_cpp/godot.hpp
  src/godot.cpp
  src/variant/char_string.cpp
Labels: enhancement, topic:gdextension

#1261 Cherry-picks for the godot-cpp 4.1 branch - 4th batch
  .github/workflows/ci.yml
  SConstruct
  binding_generator.py
  include/godot_cpp/classes/ref.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/core/memory.hpp
  include/godot_cpp/templates/cowdata.hpp
  include/godot_cpp/templates/list.hpp
  include/godot_cpp/templates/rid_owner.hpp
  include/godot_cpp/templates/thread_work_pool.hpp
  include/godot_cpp/variant/variant.hpp
  src/core/class_db.cpp
  src/core/memory.cpp
  src/godot.cpp
  src/variant/variant.cpp
  test/project/example.gdextension
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
  tools/javascript.py
Labels: bug, enhancement

#1270 [SCons] Rename javascript tool to web
  .github/workflows/ci.yml
  test/project/example.gdextension
  tools/godotcpp.py
  tools/web.py
Labels: enhancement, platform:web, topic:buildsystem

#1266 Automatically register only engine classes whose header has been included
  binding_generator.py
  include/godot_cpp/classes/editor_plugin_registration.hpp
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/godot.hpp
  src/classes/editor_plugin_registration.cpp
  src/classes/wrapped.cpp
  src/godot.cpp
Labels: bug, topic:gdextension, cherrypick:4.1

#1258 Let `gdextension_dir` function as standalone argument
  tools/godotcpp.py
Labels: enhancement, topic:buildsystem, topic:gdextension, cherrypick:4.1

#1275 clang: Add CallableCustomMethodPointerBase virtual destructor
  include/godot_cpp/variant/callable_method_pointer.hpp
Labels: bug

#1230 Refactor compiledb implementation
  tools/godotcpp.py
Labels: topic:buildsystem, cherrypick:4.1

#1253 Fix return value and `r_valid` value in `Variant::iter_init` and `Variant::iter_next`
  src/variant/variant.cpp
Labels: bug, cherrypick:4.1

#1216 SCons: Disable C++ exception handling by default
  CMakeLists.txt
  test/CMakeLists.txt
  tools/godotcpp.py
  tools/windows.py
Labels: enhancement, needs testing, topic:buildsystem, cherrypick:4.1

#1278 Add test for `Callable.bind()`
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
Labels: enhancement

#1279 Add protections against registering classes that didn't use `GDCLASS()`
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/class_db.hpp
Labels: bug, cherrypick:4.1

#1277 Add an automated test using a Variant iterator
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
Labels: enhancement

#1286 Switch to using `ObjectID` in custom callables
  gdextension/gdextension_interface.h
  src/variant/callable_method_pointer.cpp
Labels: enhancement
