Repository godotengine/godot-cpp, pull requests merged in 2023-12, with the labels that each got.

#1323 Prevent `-Wtype-limits` warning on GCC 11 due to unsigned comparison
  src/godot.cpp
Labels: bug, cherrypick:4.1, cherrypick:4.2

#1324 CMake: Remove hardcoded warnings list and forcing -Werror on library builds
  CMakeLists.txt
  test/CMakeLists.txt
Labels: enhancement, topic:buildsystem, cherrypick:4.1, cherrypick:4.2

#1340 Add PackedRealArray as an alias for PackedFloat(32/64)Array
  include/godot_cpp/variant/variant.hpp
Labels: enhancement, cherrypick:4.2

#1339 Allow detecting when building as a GDExtension
  tools/godotcpp.py
Labels: enhancement, topic:gdextension
