Repository godotengine/godot-cpp, pull requests merged in 2023-07, with the labels that each got.

#1168 [3.x] Bump Ubuntu version on CI from 18.04 to 20.04
  .github/workflows/ci.yml
Labels: topic:buildsystem, cherrypick:3.5

#1175 [MSVC] Force UTF-8 encoding.
  CMakeLists.txt
  tools/windows.py
Labels: bug, platform:windows, topic:buildsystem, topic:gdextension

#1170 Import `env` if possible
  SConstruct
Labels: enhancement, topic:buildsystem

#1172 Add lower-case "*.cache" in ".gitignore"
  .gitignore
Labels: enhancement, topic:buildsystem

#1176 In generated methods, only allocate the method StringName the first time
  binding_generator.py
Labels: bug

#1150 Attempt to fully implement CharString
  include/godot_cpp/templates/cowdata.hpp
  include/godot_cpp/variant/char_string.hpp
  src/variant/char_string.cpp
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
Labels: enhancement

#1186 Add support for indexed properties
  gdextension/gdextension_interface.h
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/core/object.hpp
  include/godot_cpp/godot.hpp
  src/core/class_db.cpp
  src/godot.cpp
Labels: enhancement

#1184 Don't call parent _get_property_list when a class doesn't define it (for internal binding).
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/class_db.hpp
  src/classes/wrapped.cpp
Labels: bug, topic:gdextension

#1181 Don't cache `null` forever if a singleton isn't available yet
  binding_generator.py
Labels: bug, topic:gdextension, cherrypick:4.1

#1188 Add platform macros
  tools/android.py
  tools/ios.py
  tools/javascript.py
  tools/linux.py
  tools/macos.py
  tools/windows.py
Labels: enhancement, topic:buildsystem, cherrypick:4.1

#1189 [SCons] Add option to generate a compilation database.
  SConstruct
Labels: enhancement, topic:buildsystem, cherrypick:4.1

#1191 [SCons] Merge OSXCross tools into platform ones
  tools/ios.py
  tools/ios_osxcross.py
  tools/macos.py
  tools/macos_osxcross.py
Labels: enhancement, topic:buildsystem, cherrypick:4.1

#1166 Implement `String::resize()` in godot-cpp
  binding_generator.py
  gdextension/gdextension_interface.h
  include/godot_cpp/godot.hpp
  src/godot.cpp
  src/variant/char_string.cpp
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
Labels: enhancement
