Repository godotengine/godot-cpp, pull requests merged in 2023-08, with the labels that each got.

#1203 Statically link mingw/msvc runtime libraries on Windows
  tools/targets.py
  tools/windows.py
Labels: bug, enhancement, topic:buildsystem

#1193 Added generated version header
  binding_generator.py
Labels: cherrypick:4.1

#1205 Cherry-picks for the godot-cpp 4.1 branch - 1st batch
  SConstruct
  binding_generator.py
  include/godot_cpp/templates/cowdata.hpp
  include/godot_cpp/variant/char_string.hpp
  src/variant/char_string.cpp
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
  tools/android.py
  tools/ios.py
  tools/ios_osxcross.py
  tools/javascript.py
  tools/linux.py
  tools/macos.py
  tools/macos_osxcross.py
  tools/targets.py
  tools/windows.py
Labels: bug, enhancement

#1209 Add automated tests to verify some previous fixes
  test/project/main.gd
  test/project/project.godot
  test/src/example.cpp
  test/src/example.h
Labels: bug, enhancement, cherrypick:4.1

#1211 Fix Clang deprecated builtins
  include/godot_cpp/templates/cowdata.hpp
Labels: bug

#1215 Fix forgotten not operator
  include/godot_cpp/templates/cowdata.hpp
Labels: bug, regression

#1204 SCons: Sync `targets.py` fully with upstream Godot
  tools/targets.py
Labels: enhancement, topic:buildsystem, cherrypick:4.1

#1197 Add remaining component-wise `min/max` functions to `Vector*`
  include/godot_cpp/variant/vector3.hpp
  include/godot_cpp/variant/vector3i.hpp
  include/godot_cpp/variant/vector4.hpp
  include/godot_cpp/variant/vector4i.hpp
Labels: enhancement, cherrypick:4.1

#1218 Fix link to test project in readme
  README.md
Labels: bug, documentation, cherrypick:4.1

#1225 Add support for placeholder_script_instance_create/update
  gdextension/gdextension_interface.h
  include/godot_cpp/godot.hpp
  src/godot.cpp
Labels: enhancement

#1190 [SCons] Move the GodotCPP build to its own tool.
  SConstruct
  tools/godotcpp.py
Labels: enhancement, topic:buildsystem, cherrypick:4.1

#1151 Fix `Object::notification` order (cpp-bindings)
  gdextension/gdextension_interface.h
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/godot.hpp
  src/godot.cpp
Labels: bug

#1226 Fix formatting of `compatibility_minimum` examples
  README.md
  test/project/example.gdextension
Labels: bug, documentation, cherrypick:4.1
