Repository godotengine/godot-cpp, pull requests merged in 2023-02, with the labels that each got.

#1008 {cmake} Use the same compiler warnings as godot
  CMakeLists.txt
  cmake/GodotCompilerWarnings.cmake
Labels: enhancement, cmake, buildsystem

#1011 Update error macros to match core
  gdextension/gdextension_interface.h
  include/godot_cpp/core/error_macros.hpp
  src/core/error_macros.cpp
  src/variant/transform2d.cpp
Labels: bug, enhancement

#1027 Fix global enum cast and add `Varint::Type`'s cast.
  binding_generator.py
Labels: bug

#1028 Fix improper implicit conversion
  test/src/example.cpp
Labels: bug

#1029 {cmake} Combine target_include_directories
  CMakeLists.txt
Labels: enhancement, cmake, buildsystem

#1030 ExampleRef::get_id() should be const
  test/src/example.cpp
  test/src/example.h
Labels: enhancement

#975 {cmake} Use STATIC and POSITION_INDEPENDENT_CODE
  CMakeLists.txt
  cmake/GodotCompilerWarnings.cmake
Labels: enhancement, cmake, buildsystem

#1034 `array_set_typed()` now called with `GDExtensionVariantType` instead of `uint32_t`
  src/variant/packed_arrays.cpp
Labels: enhancement

#1037 Fix Object::cast_to<T>() for custom classes
  include/godot_cpp/core/object.hpp
Labels: bug

#1040 Fix compilation error: const GDExtensionStringPtr -> GDExtensionConst…
  src/classes/low_level.cpp
  src/variant/char_string.cpp
Labels: bug

#1046 Revert "Fix Object::cast_to<T>() for custom classes"
  include/godot_cpp/core/object.hpp
Labels: bug, crash, regression

#1053 Fix incorrect memory allocation in release builds.
  .github/workflows/ci.yml
  include/godot_cpp/core/memory.hpp
  include/godot_cpp/templates/cowdata.hpp
  src/core/memory.cpp
Labels: bug, gdextension
