Repository godotengine/godot-cpp, pull requests merged in 2023-11, with the labels that each got.

#1291 Update the environment variables used to access the Android NDK toolchain
  tools/android.py
Labels: enhancement, platform:android, topic:buildsystem, cherrypick:4.1

#1292 `GDCLASS` synced by ending with "private:"
  include/godot_cpp/classes/wrapped.hpp
Labels: bug, cherrypick:4.1

#1303 Fix `is_msvc` and `use_hot_reload` variables
  tools/godotcpp.py
Labels: bug, topic:buildsystem, cherrypick:4.1

#1301 ignoring venv in .gitignore
  .gitignore
Labels: enhancement, topic:buildsystem, cherrypick:4.1

#1302 [iOS] Fix building as static library or xcframework, add iOS config and xcframework build script to the test project.
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/memory.hpp
  src/core/memory.cpp
  test/SConstruct
  test/generate_xcframework.sh
  test/project/bin/libgdexample.macos.template_debug.framework/Resources/Info.plist
  test/project/bin/libgdexample.macos.template_release.framework/Resources/Info.plist
  test/project/example.gdextension
  test/project/project.godot
Labels: bug, platform:ios

#1304 Revert "Hack adding `--quit-after 100` to ensure extension_list.cfg gets generated"
  .github/workflows/ci.yml
Labels: bug

#1308 CI: Workaround upstream issue with .NET editor build not exiting
  .github/workflows/ci.yml
Labels: bug, topic:buildsystem, cherrypick:4.0, cherrypick:4.1

#1306 Cherry-picks for the godot-cpp 4.1 branch - 6th batch
  .gitignore
  include/godot_cpp/classes/wrapped.hpp
  tools/android.py
  tools/godotcpp.py
Labels: bug, enhancement

#1298 Add missing int→Variant conversions
  include/godot_cpp/variant/variant.hpp
  src/variant/variant.cpp
Labels: bug, cherrypick:4.1

#1294 Fix comparison of `Callable`s from `callable_mp()` of the same method
  include/godot_cpp/variant/callable_method_pointer.hpp
  src/variant/callable_method_pointer.cpp
  test/project/main.gd
Labels: bug

#1314 CI: Install Android NDK r23c explicitly
  .github/workflows/ci.yml
Labels: bug, platform:android, topic:buildsystem, cherrypick:3.x, cherrypick:3.5, cherrypick:4.0, cherrypick:4.1

#1315 [iOS] Bump default version to 12 to match engine.
  tools/ios.py
Labels: enhancement, platform:ios, topic:buildsystem, topic:gdextension

#1318 [Scons] Set the minimum Android API level to 21
  tools/android.py
Labels: bug, platform:android

#1316 [iOS] Fix initialisation/termination of multiple statically linked extensions.
  include/godot_cpp/godot.hpp
  src/godot.cpp
Labels: bug, cherrypick:4.1

#1288 Make CMake only include debug symbols when appropriate
  CMakeLists.txt
Labels: bug, topic:buildsystem, cherrypick:4.1

#1307 Fix file list issues when trying to build with meson via cmake
  CMakeLists.txt
  binding_generator.py
Labels: bug, topic:buildsystem, cherrypick:4.1

#1320 Change bit field enums to use `uint64_t` as underlying type
  binding_generator.py
Labels: bug, topic:buildsystem

#1321 Send NOTIFICATION_POSTINITIALIZE to extension classes
  src/classes/wrapped.cpp
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
Labels: bug, cherrypick:4.1
