Repository godotengine/godot-cpp, pull requests merged in 2023-05, with the labels that each got.

#1108 Moved cmake_minimum_required() call to top
  CMakeLists.txt
Labels: bug

#1095 Update to load function pointers for GDExtension interface
  binding_generator.py
  gdextension/gdextension_interface.h
  include/godot_cpp/classes/ref.hpp
  include/godot_cpp/core/binder_common.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/core/engine_ptrcall.hpp
  include/godot_cpp/core/memory.hpp
  include/godot_cpp/core/method_ptrcall.hpp
  include/godot_cpp/core/object.hpp
  include/godot_cpp/godot.hpp
  src/classes/low_level.cpp
  src/classes/wrapped.cpp
  src/core/class_db.cpp
  src/core/error_macros.cpp
  src/core/memory.cpp
  src/core/method_bind.cpp
  src/godot.cpp
  src/variant/char_string.cpp
  src/variant/packed_arrays.cpp
  src/variant/variant.cpp
  test/demo/example.gdextension
  test/src/register_types.cpp
Labels: enhancement, gdextension

#1115 Update Getting Started section of README.md
  README.md
Labels: documentation, topic:gdextension

#1050 Ensure GDExtension class is the correct type for the Godot engine class
  binding_generator.py
  gdextension/gdextension_interface.h
  include/godot_cpp/classes/ref.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/core/engine_ptrcall.hpp
  include/godot_cpp/core/method_ptrcall.hpp
  include/godot_cpp/core/object.hpp
  include/godot_cpp/godot.hpp
  src/core/class_db.cpp
  src/core/object.cpp
  src/godot.cpp
  src/variant/variant.cpp
Labels: bug

#1116 Change Ref<T> to allow non const access to ptr
  include/godot_cpp/classes/ref.hpp
Labels: bug

#1101 Add automated tests that run a GDExtension (rather than just building it)
  .github/workflows/ci.yml
  test/README.md
  test/SConstruct
  test/demo/main.gd
  test/project/bin/libgdexample.osx.template_debug.framework/Resources/Info.plist
  test/project/bin/libgdexample.osx.template_release.framework/Resources/Info.plist
  test/project/default_env.tres
  test/project/example.gdextension
  test/project/icon.png
  test/project/icon.png.import
  test/project/main.gd
  test/project/main.tscn
  test/project/project.godot
  test/project/test_base.gd
  test/run-tests.sh
  test/src/example.cpp
  test/src/example.h
Labels: enhancement

#1114 Add support for adding/removing editor plugins
  binding_generator.py
  gdextension/gdextension_interface.h
  include/godot_cpp/godot.hpp
  src/godot.cpp
Labels: enhancement

#1117 Synchronize gdextension_interface.h with Godot
  gdextension/gdextension_interface.h
Labels: bug, topic:gdextension

#1113 Add issue template based on the main Godot repository
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: enhancement
