Repository godotengine/godot-cpp, pull requests merged in 2023-01, with the labels that each got.

#987 Fix enum return value size.
  binding_generator.py
Labels: bug, gdextension

#981 [3.x] [SCons] Backport SCons generator, cache.
  .github/actions/godot-cache/action.yml
  .github/workflows/ci.yml
  .gitignore
  SConstruct
  binding_generator.py
  misc/scripts/check_get_file_list.py
Labels: enhancement, buildsystem

#989 Allow method binds to take Object subclasses as arguments
  include/godot_cpp/core/binder_common.hpp
  test/demo/main.gd
  test/src/example.cpp
  test/src/example.h
Labels: bug, gdextension

#988 Rename `float=64` build option to `precision=double`
  .github/workflows/ci.yml
  CMakeLists.txt
  SConstruct
  binding_generator.py
  misc/scripts/check_get_file_list.py
Labels: enhancement, breaks compat, buildsystem

#990 CI: Use clang-format 15
  .github/workflows/static_checks.yml
Labels: buildsystem

#950 Added property info for Object's and Ref's and ported the implementation of the `check` method
  include/godot_cpp/classes/ref.hpp
  include/godot_cpp/core/binder_common.hpp
  include/godot_cpp/core/type_info.hpp
Labels: bug, enhancement

#991 Fix spelling in demo script
  test/demo/main.gd
Labels: bug

#983 Add conversions between `Variant` and `ObjectID`
  include/godot_cpp/variant/variant.hpp
  src/variant/variant.cpp
Labels: enhancement

#997 Fix a shadowed enum (EulerOrder)
  include/godot_cpp/variant/basis.hpp
  src/variant/quaternion.cpp
Labels: bug

#1000 Fix Variant::can_convert[_strict] returning gibberish.
  src/variant/variant.cpp
Labels: bug, gdextension

#998 "Wrapped" has virtual functions so it should have a virtual destructor.
  include/godot_cpp/classes/wrapped.hpp
Labels: bug

#808 Add a more prominent warning about repository branches in README
  README.md
Labels: enhancement

#965 Fix GDCLASS needs explicit ClassDB fwd declaration
  include/godot_cpp/classes/wrapped.hpp
Labels: enhancement

#1002 {cmake} Add GODOT_CPP_SYSTEM_HEADERS option to mark includes as SYSTEM
  CMakeLists.txt
Labels: enhancement, cmake, buildsystem

#1004 Remove unused ucaps header
  binding_generator.py
  include/godot_cpp/variant/ucaps.hpp
Labels: enhancement

#1005 Fix some sign comparison warnings
  include/godot_cpp/core/method_bind.hpp
Labels: bug

#1003 Change behavior of Math::sign to match Godot builtin
  include/godot_cpp/core/math.hpp
Labels: bug, breaks compat

#1018 Support typed array default values in extension API
  binding_generator.py
  include/godot_cpp/core/memory.hpp
Labels: enhancement, buildsystem

#956 Fixed `VARIANT_ENUM/BITFIELD_CAST` to show the correct names
  binding_generator.py
  include/godot_cpp/core/binder_common.hpp
  include/godot_cpp/core/type_info.hpp
  test/demo/main.gd
  test/src/example.cpp
  test/src/example.h
Labels: bug, breaks compat

#982 Add missing local_vector.hpp template
  include/godot_cpp/templates/local_vector.hpp
Labels: enhancement

#1023 Move DefaultTypedAllocator after memdelete
  include/godot_cpp/core/memory.hpp
Labels: bug

#977 Binding generator cleanups
  binding_generator.py
Labels: enhancement
