Repository godotengine/godot-cpp, pull requests merged in 2023-06, with the labels that each got.

#1137 Clarify error message because there isn't a legacy Godot 4.0 mode anymore
  src/godot.cpp
Labels: usability

#1128 Fixing #1127 by making return types of auto-generated functions dynamic
  binding_generator.py
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
Labels: bug

#1139 Prepend PATH to scons env to allow use of buildroot
  SConstruct
Labels: enhancement, topic:buildsystem

#1048 Identifiers containing double underscore are reserved according to the C++ standard
  binding_generator.py
  include/godot_cpp/classes/ref.hpp
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/core/method_bind.hpp
  include/godot_cpp/core/type_info.hpp
  src/core/object.cpp
Labels: bug, topic:gdextension

#1148 GDExtension: `Uninitialized*Ptr` for constructors/converters using placement new
  gdextension/gdextension_interface.h
Labels: bug, topic:gdextension

#1086 Fix: Include method_ptrcall.hpp on simple structs.
  binding_generator.py
Labels: bug

#1047 Unregister custom classes in reverse registration order
  include/godot_cpp/core/class_db.hpp
  src/core/class_db.cpp
Labels: bug, topic:gdextension

#1159 Remove unused free-standing `initialize_level` and `deinitialize_level`
  src/godot.cpp
Labels: enhancement
