Repository godotengine/godot-cpp, pull requests merged in 2024-10, with the labels that each got.

#1595 Re-Structure cmake solution to be closer to the scons solution.
  CMakeLists.txt
  cmake/common_compiler_flags.cmake
  cmake/godotcpp.cmake
  doc/cmake.md
Labels: cmake, topic:buildsystem, cherrypick:4.2, cherrypick:4.3

#1602 [SCons] Remove use_clang_cl windows flag in favor of generic use_llvm
  tools/windows.py
Labels: enhancement, platform:windows, topic:buildsystem, cherrypick:4.2, cherrypick:4.3

#1625 Add `p_use_model_front` to `Basis::looking_at()`
  include/godot_cpp/variant/basis.hpp
  src/variant/basis.cpp
Labels: enhancement, cherrypick:4.2, cherrypick:4.3

#1630 Sync `Quaternion` with the version in Godot
  include/godot_cpp/variant/quaternion.hpp
  src/variant/quaternion.cpp
Labels: enhancement, cherrypick:4.2, cherrypick:4.3

#1574 Allow unicode class names
  .github/workflows/ci.yml
  include/godot_cpp/classes/wrapped.hpp
  test/CMakeLists.txt
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
  test/src/register_types.cpp
Labels: enhancement

#1591 Directly get object instance ID from `Variant` and implement `Variant::get_validated_object()`
  gdextension/gdextension_interface.h
  include/godot_cpp/godot.hpp
  include/godot_cpp/variant/variant.hpp
  src/godot.cpp
  src/variant/variant.cpp
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
Labels: enhancement

#1622 CI: Add `runner` workflow to call other workflows
  .github/actions/godot-cache-restore/action.yml
  .github/actions/godot-cache-save/action.yml
  .github/workflows/ci.yml
  .github/workflows/runner.yml
  .github/workflows/static_checks.yml
Labels: enhancement, topic:buildsystem, cherrypick:4.2, cherrypick:4.3

#1626 Remove unimplemented static variant functions 'blend' and 'interpolate'…
  include/godot_cpp/variant/variant.hpp
Labels: bug, cherrypick:4.2, cherrypick:4.3

#1568 Update for new NOTIFICATION_POSTINITIALIZE handling
  gdextension/gdextension_interface.h
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/godot.hpp
  src/classes/wrapped.cpp
  src/godot.cpp
Labels: enhancement

#1631 Cherry-picks for the godot-cpp 4.2 branch - 8th batch
  .github/workflows/ci.yml
  .gitignore
  CMakeLists.txt
  cmake/common_compiler_flags.cmake
  cmake/godotcpp.cmake
  doc/cmake.md
  include/godot_cpp/variant/basis.hpp
  src/variant/basis.cpp
  test/SConstruct
  tools/common_compiler_flags.py
  tools/godotcpp.py
  tools/windows.py
Labels: bug, enhancement

#1632 Cherry-picks for the godot-cpp 4.3 branch - 2nd batch
  .github/workflows/ci.yml
  .gitignore
  CMakeLists.txt
  cmake/common_compiler_flags.cmake
  cmake/godotcpp.cmake
  doc/cmake.md
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/variant/basis.hpp
  src/classes/wrapped.cpp
  src/variant/basis.cpp
  test/SConstruct
  tools/common_compiler_flags.py
  tools/godotcpp.py
  tools/web.py
  tools/windows.py
Labels: bug, enhancement

#1609 Rename Vector4.components -> coords.
  include/godot_cpp/variant/vector4.hpp
Labels: enhancement, cherrypick:4.2, cherrypick:4.3
