Repository godotengine/godot-cpp, pull requests merged in 2024-11, with the labels that each got.

#1639 [Web] Don't cache emsdk
  .github/workflows/ci.yml
Labels: bug, enhancement, topic:buildsystem, cherrypick:3.x, cherrypick:3.5, cherrypick:4.0, cherrypick:4.1, cherrypick:4.2, cherrypick:4.3

#1598 Modernise existing cmake options
  .github/workflows/ci.yml
  .gitignore
  CMakeLists.txt
  cmake/android.cmake
  cmake/common_compiler_flags.cmake
  cmake/emsdkHack.cmake
  cmake/godotcpp.cmake
  cmake/ios.cmake
  cmake/linux.cmake
  cmake/macos.cmake
  cmake/web.cmake
  cmake/windows.cmake
  doc/cmake.md
  doc/cmake.rst
  test/CMakeLists.txt
Labels: enhancement, cmake

#1617 Use namespace in defs.hpp
  include/godot_cpp/core/defs.hpp
Labels: enhancement, cherrypick:4.2, cherrypick:4.3

#1647 CMake: Align MSVC runtime (MD[d], MT) options to engine
  cmake/windows.cmake
  tools/windows.py
Labels: cmake, topic:buildsystem

#1649 CMake: fix break for build prior to modernisation PR
  cmake/godotcpp.cmake
Labels: cmake, topic:buildsystem

#1654 Update gdextension_interface.h. Add metadata to GetTypeInfo of char16_t and char32_t.
  gdextension/gdextension_interface.h
  include/godot_cpp/core/type_info.hpp
Labels: enhancement

#1653 Add `print_line` for compatibility with engine modules
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/core/print_string.hpp
  src/core/print_string.cpp
Labels: enhancement, cherrypick:4.3
