Repository godotengine/godot-cpp, pull requests merged in 2024-03, with the labels that each got.

#1404 Fix crash on virtual method calls
  binding_generator.py
Labels: bug, crash, topic:buildsystem

#1381 Fix `_notification()` with parent and child classes
  include/godot_cpp/classes/wrapped.hpp
  test/project/main.gd
  test/project/main.tscn
  test/src/example.cpp
  test/src/example.h
  test/src/register_types.cpp
Labels: bug, cherrypick:4.1, cherrypick:4.2

#1407 Fix invalid `void` return in `BitField`
  include/godot_cpp/core/type_info.hpp
Labels: bug, cherrypick:4.1, cherrypick:4.2

#1412 Use explicit `::godot` namespace in gdvirtual.gen.inc
  binding_generator.py
Labels: bug

#1399 [Packed*Array] Add support for initializer lists.
  binding_generator.py
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
Labels: enhancement, usability, cherrypick:4.1, cherrypick:4.2

#1375 Add support for getting argument count from `Callable`s
  gdextension/gdextension_interface.h
  include/godot_cpp/godot.hpp
  include/godot_cpp/variant/callable_custom.hpp
  include/godot_cpp/variant/callable_method_pointer.hpp
  src/godot.cpp
  src/variant/callable_custom.cpp
  src/variant/callable_method_pointer.cpp
  test/project/main.gd
  test/src/example.cpp
Labels: enhancement, topic:gdextension

#1397 Load new `script_instance_create3` GDExtension interface function
  gdextension/gdextension_interface.h
  include/godot_cpp/godot.hpp
  src/godot.cpp
Labels: enhancement

#1379 Avoid creating most objects that Godot is going to use placement new to initialize (mark 2)
  binding_generator.py
  include/godot_cpp/variant/variant.hpp
  src/variant/variant.cpp
Labels: bug, cherrypick:4.1, cherrypick:4.2
