Repository godotengine/godot-cpp, pull requests merged in 2024-09, with the labels that each got.

#1548 Add hot reload support when building with GCC and CMake
  CMakeLists.txt
Labels: enhancement, cherrypick:4.2, cherrypick:4.3

#1535 Add support for LLVM/MinGW and ARM64 Windows builds.
  tools/common_compiler_flags.py
  tools/windows.py
Labels: enhancement, platform:windows, topic:buildsystem, cherrypick:4.2, cherrypick:4.3

#1563 Add visibility-hidden to CMake build
  CMakeLists.txt
Labels: bug, cmake, topic:buildsystem, cherrypick:4.2, cherrypick:4.3

#1572 Cherry-picks for the godot-cpp 4.1 branch - 13th batch
  .github/actions/godot-cache-restore/action.yml
  .github/actions/godot-cache-save/action.yml
  .github/workflows/ci.yml
  binding_generator.py
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/type_info.hpp
  include/godot_cpp/templates/safe_refcount.hpp
  test/project/example.gdextension
  test/src/example.cpp
  test/src/example.h
  tools/godotcpp.py
  tools/ios.py
  tools/web.py
Labels: bug, enhancement

#1570 Cherry-picks for the godot-cpp 4.2 branch - 7th batch
  .github/actions/godot-cache-restore/action.yml
  .github/actions/godot-cache-save/action.yml
  .github/workflows/ci.yml
  CMakeLists.txt
  binding_generator.py
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/templates/safe_refcount.hpp
  test/project/example.gdextension
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
  tools/godotcpp.py
  tools/ios.py
  tools/web.py
Labels: bug, enhancement

#1569 Cherry-picks for the godot-cpp 4.3 branch - 1st batch
  binding_generator.py
  include/godot_cpp/core/type_info.hpp
  include/godot_cpp/templates/safe_refcount.hpp
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
  tools/web.py
Labels: bug, enhancement

#1583 Updated all variable names to use GODOT_ prefix
  CMakeLists.txt
  cmake/GodotCompilerWarnings.cmake
Labels: cmake, topic:buildsystem

#1162 Implement typed dictionaries
  binding_generator.py
  include/godot_cpp/core/type_info.hpp
  include/godot_cpp/godot.hpp
  include/godot_cpp/variant/typed_dictionary.hpp
  src/godot.cpp
  src/variant/packed_arrays.cpp
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
Labels: enhancement

#1603 [SCons] Enable WASM_BIGINT in web builds
  tools/web.py
Labels: bug, platform:web, topic:buildsystem, cherrypick:4.3

#1592 [4.3] Revert "Unexpose `UtilityFunctions::is_instance_valid()`"
  binding_generator.py
Labels: bug, regression, cherrypick:4.1, cherrypick:4.2

#1599 Update .gitignore to add .idea for the Jetbrains CLion IDE
  .gitignore
Labels: enhancement, cherrypick:4.2, cherrypick:4.3
