Repository godotengine/godot-cpp, pull requests merged in 2024-01, with the labels that each got.

#1344 Add an error message if android NDK is not installed
  tools/android.py
Labels: platform:android, topic:buildsystem, cherrypick:4.1, cherrypick:4.2

#1346 Fix expected argument count for call errors
  include/godot_cpp/core/binder_common.hpp
Labels: bug, topic:gdextension, cherrypick:4.2

#1347 Add `Vector2i/3i/4i` methods: `distance_to` and `distance_squared_to`
  include/godot_cpp/variant/vector2i.hpp
  include/godot_cpp/variant/vector3i.hpp
  include/godot_cpp/variant/vector4i.hpp
  src/variant/vector2i.cpp
Labels: enhancement

#1349 Add missing `OP_POWER` operator to `Variant`
  binding_generator.py
  include/godot_cpp/variant/variant.hpp
Labels: bug, cherrypick:4.1, cherrypick:4.2

#1351 Remove "godot" namespace when binding global constants.
  binding_generator.py
Labels: bug, cherrypick:4.1, cherrypick:4.2

#1360 Fix `AABB.encloses` failing on shared upper bound
  include/godot_cpp/variant/aabb.hpp
Labels: bug, cherrypick:4.2

#1359 Rework GDCLASS macro to allow abstract classes
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/class_db.hpp
  test/src/example.h
  test/src/register_types.cpp
Labels: bug, topic:buildsystem, cherrypick:4.2

#1357 Switch to 64-bit ints.
  binding_generator.py
  include/godot_cpp/templates/cowdata.hpp
  include/godot_cpp/templates/safe_refcount.hpp
  include/godot_cpp/templates/vector.hpp
  include/godot_cpp/variant/char_string.hpp
  src/variant/char_string.cpp
  src/variant/packed_arrays.cpp
Labels: enhancement, topic:gdextension, cherrypick:4.1, cherrypick:4.2
