Repository godotengine/godot-cpp, pull requests merged in 2024-05, with the labels that each got.

#1437 Add scalar versions of `Vector*` `min/max/clamp/snap(ped)`
  include/godot_cpp/variant/aabb.hpp
  include/godot_cpp/variant/rect2.hpp
  include/godot_cpp/variant/rect2i.hpp
  include/godot_cpp/variant/vector2.hpp
  include/godot_cpp/variant/vector2i.hpp
  include/godot_cpp/variant/vector3.hpp
  include/godot_cpp/variant/vector3i.hpp
  include/godot_cpp/variant/vector4.hpp
  include/godot_cpp/variant/vector4i.hpp
  src/variant/vector2.cpp
  src/variant/vector2i.cpp
  src/variant/vector3.cpp
  src/variant/vector3i.cpp
  src/variant/vector4.cpp
  src/variant/vector4i.cpp
Labels: enhancement, topic:gdextension

#1374 Allow submitting documentation to the Godot editor
  gdextension/gdextension_interface.h
  include/godot_cpp/core/method_bind.hpp
  include/godot_cpp/godot.hpp
  src/godot.cpp
  test/SConstruct
  test/doc_classes/Example.xml
  test/project/project.godot
  tools/godotcpp.py
Labels: enhancement

#1450 Update `free_property_list` callback to take count
  gdextension/gdextension_interface.h
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/class_db.hpp
Labels: enhancement

#1460 [4.2] Backport miscellaneous changes that can't be cherry-picked
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/method_bind.hpp
Labels: bug, cherrypick:4.1

#1461 Attempt to fix recent CI failures on `master` branch
  .github/workflows/ci.yml
Labels: bug, topic:buildsystem

#1458 Clean up instance bindings for engine singletons to prevent crash
  binding_generator.py
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/godot.hpp
  src/core/class_db.cpp
  src/godot.cpp
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
Labels: bug, crash, cherrypick:4.2

#1457 [Core] Reduce and prevent unnecessary random-access to `List`
  include/godot_cpp/templates/list.hpp
Labels: enhancement

#1451 [SCons] Add option to build without threads
  test/project/example.gdextension
  tools/godotcpp.py
  tools/web.py
Labels: enhancement, platform:web, topic:buildsystem

#1463 Mark return value of `get_class_static` and `get_parent_class_static` as const.
  include/godot_cpp/classes/wrapped.hpp
Labels: enhancement, cherrypick:4.1, cherrypick:4.2

#1447 Fix NOTIFICATION_POSTINITIALIZE sent twice to native parent classes
  include/godot_cpp/classes/wrapped.hpp
  src/classes/wrapped.cpp
Labels: bug, cherrypick:4.1, cherrypick:4.2

#1465 Cherry-picks for the godot-cpp 4.2 branch - 4th batch
  binding_generator.py
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/core/math.hpp
  include/godot_cpp/core/method_ptrcall.hpp
  include/godot_cpp/core/property_info.hpp
  include/godot_cpp/core/type_info.hpp
  include/godot_cpp/godot.hpp
  include/godot_cpp/variant/aabb.hpp
  include/godot_cpp/variant/basis.hpp
  include/godot_cpp/variant/plane.hpp
  include/godot_cpp/variant/quaternion.hpp
  include/godot_cpp/variant/rect2.hpp
  include/godot_cpp/variant/transform2d.hpp
  include/godot_cpp/variant/transform3d.hpp
  include/godot_cpp/variant/vector2.hpp
  include/godot_cpp/variant/vector3.hpp
  include/godot_cpp/variant/vector4.hpp
  src/classes/wrapped.cpp
  src/core/class_db.cpp
  src/core/object.cpp
  src/godot.cpp
  src/variant/aabb.cpp
  src/variant/basis.cpp
  src/variant/plane.cpp
  src/variant/quaternion.cpp
  src/variant/rect2.cpp
  src/variant/transform2d.cpp
  src/variant/transform3d.cpp
  src/variant/vector2.cpp
  src/variant/vector3.cpp
  src/variant/vector4.cpp
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
Labels: bug, enhancement

#1466 Cherry-picks for the godot-cpp 4.1 branch - 10th batch
  binding_generator.py
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/core/math.hpp
  include/godot_cpp/core/method_bind.hpp
  include/godot_cpp/core/method_ptrcall.hpp
  include/godot_cpp/core/property_info.hpp
  include/godot_cpp/core/type_info.hpp
  include/godot_cpp/variant/aabb.hpp
  include/godot_cpp/variant/basis.hpp
  include/godot_cpp/variant/plane.hpp
  include/godot_cpp/variant/quaternion.hpp
  include/godot_cpp/variant/rect2.hpp
  include/godot_cpp/variant/transform2d.hpp
  include/godot_cpp/variant/transform3d.hpp
  include/godot_cpp/variant/vector2.hpp
  include/godot_cpp/variant/vector3.hpp
  include/godot_cpp/variant/vector4.hpp
  src/classes/wrapped.cpp
  src/core/object.cpp
  src/variant/aabb.cpp
  src/variant/basis.cpp
  src/variant/plane.cpp
  src/variant/quaternion.cpp
  src/variant/rect2.cpp
  src/variant/transform2d.cpp
  src/variant/transform3d.cpp
  src/variant/vector2.cpp
  src/variant/vector3.cpp
  src/variant/vector4.cpp
  test/project/main.gd
Labels: bug, enhancement
