Repository godotengine/godot-cpp, pull requests merged in 2024-04, with the labels that each got.

#1409 Enforce template syntax `typename` over `class`
  binding_generator.py
  include/godot_cpp/classes/editor_plugin_registration.hpp
  include/godot_cpp/classes/ref.hpp
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/binder_common.hpp
  include/godot_cpp/core/builtin_ptrcall.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/core/defs.hpp
  include/godot_cpp/core/engine_ptrcall.hpp
  include/godot_cpp/core/math.hpp
  include/godot_cpp/core/memory.hpp
  include/godot_cpp/core/method_bind.hpp
  include/godot_cpp/core/method_ptrcall.hpp
  include/godot_cpp/core/object.hpp
  include/godot_cpp/core/type_info.hpp
  include/godot_cpp/templates/cowdata.hpp
  include/godot_cpp/templates/hash_map.hpp
  include/godot_cpp/templates/hash_set.hpp
  include/godot_cpp/templates/hashfuncs.hpp
  include/godot_cpp/templates/list.hpp
  include/godot_cpp/templates/local_vector.hpp
  include/godot_cpp/templates/pair.hpp
  include/godot_cpp/templates/rb_map.hpp
  include/godot_cpp/templates/rb_set.hpp
  include/godot_cpp/templates/rid_owner.hpp
  include/godot_cpp/templates/safe_refcount.hpp
  include/godot_cpp/templates/search_array.hpp
  include/godot_cpp/templates/self_list.hpp
  include/godot_cpp/templates/sort_array.hpp
  include/godot_cpp/templates/thread_work_pool.hpp
  include/godot_cpp/templates/vector.hpp
  include/godot_cpp/templates/vmap.hpp
  include/godot_cpp/templates/vset.hpp
  include/godot_cpp/variant/callable_method_pointer.hpp
  include/godot_cpp/variant/char_string.hpp
  include/godot_cpp/variant/typed_array.hpp
  include/godot_cpp/variant/variant.hpp
  src/variant/char_string.cpp
Labels: enhancement

#1413 Add extension support for argument count to `ScriptInstance`
  gdextension/gdextension_interface.h
Labels: enhancement, topic:gdextension

#1417 Change cmake required to v3.13
  CMakeLists.txt
  test/CMakeLists.txt
Labels: enhancement, discussion, topic:buildsystem

#1422 Fix incorrect utility call signature
  include/godot_cpp/core/engine_ptrcall.hpp
Labels: bug, topic:gdextension, cherrypick:4.1, cherrypick:4.2

#1411 Cherry-picks for the godot-cpp 4.1 branch - 8th batch
  CMakeLists.txt
  binding_generator.py
  include/godot_cpp/classes/editor_plugin_registration.hpp
  include/godot_cpp/classes/ref.hpp
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/binder_common.hpp
  include/godot_cpp/core/builtin_ptrcall.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/core/defs.hpp
  include/godot_cpp/core/engine_ptrcall.hpp
  include/godot_cpp/core/math.hpp
  include/godot_cpp/core/memory.hpp
  include/godot_cpp/core/method_bind.hpp
  include/godot_cpp/core/method_ptrcall.hpp
  include/godot_cpp/core/object.hpp
  include/godot_cpp/core/type_info.hpp
  include/godot_cpp/templates/cowdata.hpp
  include/godot_cpp/templates/hash_map.hpp
  include/godot_cpp/templates/hash_set.hpp
  include/godot_cpp/templates/hashfuncs.hpp
  include/godot_cpp/templates/list.hpp
  include/godot_cpp/templates/local_vector.hpp
  include/godot_cpp/templates/pair.hpp
  include/godot_cpp/templates/rb_map.hpp
  include/godot_cpp/templates/rb_set.hpp
  include/godot_cpp/templates/rid_owner.hpp
  include/godot_cpp/templates/safe_refcount.hpp
  include/godot_cpp/templates/search_array.hpp
  include/godot_cpp/templates/self_list.hpp
  include/godot_cpp/templates/sort_array.hpp
  include/godot_cpp/templates/thread_work_pool.hpp
  include/godot_cpp/templates/vector.hpp
  include/godot_cpp/templates/vmap.hpp
  include/godot_cpp/templates/vset.hpp
  include/godot_cpp/variant/char_string.hpp
  include/godot_cpp/variant/typed_array.hpp
  include/godot_cpp/variant/variant.hpp
  src/core/memory.cpp
  src/variant/char_string.cpp
  src/variant/packed_arrays.cpp
  src/variant/variant.cpp
  test/CMakeLists.txt
  test/project/main.gd
  test/project/main.tscn
  test/src/example.cpp
  test/src/example.h
  test/src/register_types.cpp
  tools/android.py
  tools/common_compiler_flags.py
  tools/godotcpp.py
  tools/ios.py
  tools/linux.py
  tools/macos.py
  tools/targets.py
  tools/web.py
  tools/windows.py
Labels: bug, enhancement

#1410 Cherry-picks for the godot-cpp 4.2 branch - 2nd batch
  CMakeLists.txt
  binding_generator.py
  include/godot_cpp/classes/editor_plugin_registration.hpp
  include/godot_cpp/classes/ref.hpp
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/binder_common.hpp
  include/godot_cpp/core/builtin_ptrcall.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/core/defs.hpp
  include/godot_cpp/core/engine_ptrcall.hpp
  include/godot_cpp/core/math.hpp
  include/godot_cpp/core/memory.hpp
  include/godot_cpp/core/method_bind.hpp
  include/godot_cpp/core/method_ptrcall.hpp
  include/godot_cpp/core/object.hpp
  include/godot_cpp/core/type_info.hpp
  include/godot_cpp/templates/cowdata.hpp
  include/godot_cpp/templates/hash_map.hpp
  include/godot_cpp/templates/hash_set.hpp
  include/godot_cpp/templates/hashfuncs.hpp
  include/godot_cpp/templates/list.hpp
  include/godot_cpp/templates/local_vector.hpp
  include/godot_cpp/templates/pair.hpp
  include/godot_cpp/templates/rb_map.hpp
  include/godot_cpp/templates/rb_set.hpp
  include/godot_cpp/templates/rid_owner.hpp
  include/godot_cpp/templates/safe_refcount.hpp
  include/godot_cpp/templates/search_array.hpp
  include/godot_cpp/templates/self_list.hpp
  include/godot_cpp/templates/sort_array.hpp
  include/godot_cpp/templates/thread_work_pool.hpp
  include/godot_cpp/templates/vector.hpp
  include/godot_cpp/templates/vmap.hpp
  include/godot_cpp/templates/vset.hpp
  include/godot_cpp/variant/callable_method_pointer.hpp
  include/godot_cpp/variant/char_string.hpp
  include/godot_cpp/variant/typed_array.hpp
  include/godot_cpp/variant/variant.hpp
  src/core/memory.cpp
  src/variant/char_string.cpp
  src/variant/packed_arrays.cpp
  src/variant/variant.cpp
  test/CMakeLists.txt
  test/project/main.gd
  test/project/main.tscn
  test/src/example.cpp
  test/src/example.h
  test/src/register_types.cpp
  tools/android.py
  tools/common_compiler_flags.py
  tools/godotcpp.py
  tools/ios.py
  tools/linux.py
  tools/macos.py
  tools/targets.py
  tools/web.py
  tools/windows.py
Labels: bug, enhancement

#1364 Implement `verbose` toggle from godot repo
  .github/workflows/ci.yml
  tools/godotcpp.py
Labels: enhancement, topic:buildsystem, cherrypick:4.1, cherrypick:4.2

#1438 Fix Projection create_orthogonal being incorrect
  src/variant/projection.cpp
Labels: bug, cherrypick:4.1, cherrypick:4.2

#1440 Fix PropertyInfo to use hint/usage default constants
  include/godot_cpp/core/property_info.hpp
Labels: bug, topic:gdextension, cherrypick:4.1, cherrypick:4.2

#1441 Cherry-picks for the godot-cpp 4.1 branch - 9th batch
  .github/workflows/ci.yml
  README.md
  include/godot_cpp/core/property_info.hpp
  src/variant/projection.cpp
  test/src/register_types.cpp
  tools/godotcpp.py
Labels: bug, enhancement

#1436 [Math] Add `is_finite` methods
  include/godot_cpp/core/math.hpp
  include/godot_cpp/variant/aabb.hpp
  include/godot_cpp/variant/basis.hpp
  include/godot_cpp/variant/plane.hpp
  include/godot_cpp/variant/quaternion.hpp
  include/godot_cpp/variant/rect2.hpp
  include/godot_cpp/variant/transform2d.hpp
  include/godot_cpp/variant/transform3d.hpp
  include/godot_cpp/variant/vector2.hpp
  include/godot_cpp/variant/vector3.hpp
  include/godot_cpp/variant/vector4.hpp
  src/variant/aabb.cpp
  src/variant/basis.cpp
  src/variant/plane.cpp
  src/variant/quaternion.cpp
  src/variant/rect2.cpp
  src/variant/transform2d.cpp
  src/variant/transform3d.cpp
  src/variant/vector2.cpp
  src/variant/vector3.cpp
  src/variant/vector4.cpp
Labels: enhancement, topic:gdextension, cherrypick:4.1, cherrypick:4.2

#1443 Implement to/from dict helpers for PropertyInfo/MethodInfo
  include/godot_cpp/core/property_info.hpp
  src/core/object.cpp
Labels: enhancement, topic:gdextension, cherrypick:4.1, cherrypick:4.2

#1431 Fix create instance func
  include/godot_cpp/core/class_db.hpp
Labels: enhancement, cherrypick:4.1, cherrypick:4.2

#1448 Give compile-time error if registering a class without its own `_bind_methods()` function
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/core/type_info.hpp
Labels: bug, cherrypick:4.1, cherrypick:4.2

#1405 Correctly handle `Object *` arguments that were encoded as `nullptr`
  include/godot_cpp/core/method_ptrcall.hpp
  test/project/main.gd
Labels: bug, crash, cherrypick:4.1, cherrypick:4.2

#1445 Allow forwarding from `ClassDB` to `ClassDBSingleton` to support enumerations
  binding_generator.py
  include/godot_cpp/core/class_db.hpp
Labels: bug, cherrypick:4.1, cherrypick:4.2
