Repository godotengine/godot-cpp, pull requests merged in 2024-06, with the labels that each got.

#1477 Explicitly refer to `godot` namespace in `GDREGISTER_*_CLASS()` macros
  include/godot_cpp/core/class_db.hpp
Labels: bug, cherrypick:4.1, cherrypick:4.2

#1484 Fix undefined symbol error on Linux with virtual methods that take `Node *` arguments
  include/godot_cpp/classes/ref.hpp
  include/godot_cpp/core/type_info.hpp
  test/src/example.cpp
  test/src/example.h
Labels: bug, platform:linuxbsd

#1478 Fix warnings emitted with -Wall
  src/core/class_db.cpp
  src/core/object.cpp
Labels: bug, cherrypick:4.1, cherrypick:4.2

#1486 Fix tests after upstream change to `Node::to_string()`
  test/project/main.gd
Labels: bug

#1487 Fix generating default values for `StringName`
  binding_generator.py
Labels: bug, topic:buildsystem, cherrypick:4.1, cherrypick:4.2

#1485 Fix vararg methods forwarded to the `ClassDB` singleton
  binding_generator.py
Labels: bug, enhancement, cherrypick:4.1, cherrypick:4.2

#1488 Add default argument processing for `NodePath`
  binding_generator.py
Labels: enhancement, topic:buildsystem, cherrypick:4.1, cherrypick:4.2

#1446 Set instance and instance binding in `Wrapped` constructor.
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/memory.hpp
  src/classes/wrapped.cpp
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
Labels: bug, topic:gdextension

#1493 Allow selecting Godot version to run the tests with
  .github/workflows/ci.yml
Labels: enhancement, topic:buildsystem

#1494 [4.2] Allow selecting Godot version to run the tests with
  .github/workflows/ci.yml
Labels: enhancement, topic:buildsystem

#1492 Cherry-picks for the godot-cpp 4.2 branch - 5th batch
  binding_generator.py
  include/godot_cpp/core/class_db.hpp
  src/core/class_db.cpp
  src/core/object.cpp
Labels: bug, enhancement

#1491 Cherry-picks for the godot-cpp 4.1 branch - 11th batch
  .github/workflows/ci.yml
  binding_generator.py
  include/godot_cpp/core/class_db.hpp
  src/core/class_db.cpp
  src/core/object.cpp
  tools/common_compiler_flags.py
  tools/godotcpp.py
Labels: bug, enhancement

#1167 Add support for build profiles.
  binding_generator.py
  test/build_profile.json
  tools/godotcpp.py
Labels: enhancement, topic:buildsystem, cherrypick:4.1, cherrypick:4.2

#1489 [Web] Force emcc to use "wasm" longjmp mode
  tools/web.py
Labels: enhancement, platform:web, topic:buildsystem, cherrypick:4.1, cherrypick:4.2

#1490 Enforce `p_` prefixes for arguments in binds
  binding_generator.py
Labels: enhancement, topic:buildsystem, cherrypick:4.1, cherrypick:4.2

#1423 Fix some style details in generation
  binding_generator.py
Labels: bug, topic:buildsystem, cherrypick:4.1, cherrypick:4.2

#1504 Replace legacy hooks with `pre-commit` Python tool
  .github/workflows/static_checks.yml
  .gitignore
  .pre-commit-config.yaml
  CMakeLists.txt
  SConstruct
  binding_generator.py
  include/godot_cpp/variant/array_helpers.hpp
  include/godot_cpp/variant/color_names.inc.hpp
  include/godot_cpp/variant/rect2.hpp
  include/godot_cpp/variant/rect2i.hpp
  misc/hooks/README.md
  misc/hooks/canonicalize_filename.sh
  misc/hooks/pre-commit
  misc/hooks/pre-commit-black
  misc/hooks/pre-commit-clang-format
  misc/hooks/winmessage.ps1
  misc/scripts/black_format.sh
  misc/scripts/check_ci_log.py
  misc/scripts/check_get_file_list.py
  misc/scripts/clang_format.sh
  misc/scripts/codespell.sh
  misc/scripts/copyright_headers.py
  misc/scripts/file_format.py
  misc/scripts/file_format.sh
  misc/scripts/header_guards.py
  misc/scripts/header_guards.sh
  misc/scripts/mypy.ini
  misc/scripts/mypy_check.sh
  pyproject.toml
  src/core/memory.cpp
  src/variant/basis.cpp
  src/variant/color.cpp
  test/SConstruct
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
  tools/android.py
  tools/common_compiler_flags.py
  tools/godotcpp.py
  tools/ios.py
  tools/linux.py
  tools/macos.py
  tools/my_spawn.py
  tools/web.py
  tools/windows.py
Labels: enhancement, topic:buildsystem, cherrypick:4.1, cherrypick:4.2

#1505 Fix `#include` formatting
  include/godot_cpp/templates/local_vector.hpp
  test/src/tests.h
Labels: cherrypick:4.1, cherrypick:4.2

#1507 SCons: Add `silence_msvc` option for Windows
  tools/windows.py
Labels: enhancement, platform:windows, topic:buildsystem, cherrypick:4.1, cherrypick:4.2

#1483 Fix sharing of typed arrays from constructor
  include/godot_cpp/variant/typed_array.hpp
Labels: bug, topic:gdextension, cherrypick:4.2
