Repository godotengine/godot-cpp, pull requests merged in 2024-07, with the labels that each got.

#1510 Remind developers about `memnew()` in crash message when missing binding callbacks
  src/classes/wrapped.cpp
Labels: enhancement

#1513 Unexpose `UtilityFunctions::is_instance_valid()`
  binding_generator.py
Labels: enhancement, breaks compat

#1529 Cherry-picks for the godot-cpp 4.1 branch - 12th batch
  .editorconfig
  .gitattributes
  .github/workflows/ci.yml
  .github/workflows/static_checks.yml
  .gitignore
  .pre-commit-config.yaml
  CMakeLists.txt
  SConstruct
  binding_generator.py
  include/godot_cpp/core/method_bind.hpp
  include/godot_cpp/templates/local_vector.hpp
  include/godot_cpp/variant/array_helpers.hpp
  include/godot_cpp/variant/color_names.inc.hpp
  include/godot_cpp/variant/rect2.hpp
  include/godot_cpp/variant/rect2i.hpp
  include/godot_cpp/variant/typed_array.hpp
  misc/hooks/README.md
  misc/hooks/canonicalize_filename.sh
  misc/hooks/pre-commit
  misc/hooks/pre-commit-black
  misc/hooks/pre-commit-clang-format
  misc/hooks/winmessage.ps1
  misc/scripts/black_format.sh
  misc/scripts/check_ci_log.py
  misc/scripts/check_get_file_list.py
  misc/scripts/clang_format.sh
  misc/scripts/codespell.sh
  misc/scripts/copyright_headers.py
  misc/scripts/file_format.py
  misc/scripts/file_format.sh
  misc/scripts/header_guards.py
  misc/scripts/header_guards.sh
  misc/scripts/mypy.ini
  misc/scripts/mypy_check.sh
  pyproject.toml
  src/core/memory.cpp
  src/variant/basis.cpp
  src/variant/color.cpp
  test/SConstruct
  test/build_profile.json
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
  test/src/tests.h
  tools/android.py
  tools/common_compiler_flags.py
  tools/godotcpp.py
  tools/ios.py
  tools/linux.py
  tools/macos.py
  tools/my_spawn.py
  tools/web.py
  tools/windows.py
Labels: bug, enhancement

#1533 Cherry-picks for the godot-cpp 4.0 branch - 1st batch
  .github/workflows/ci.yml
Labels: bug, topic:buildsystem

#1519 [CI] Upload build cache before running tests
  .github/actions/godot-cache-restore/action.yml
  .github/actions/godot-cache-save/action.yml
  .github/workflows/ci.yml
Labels: enhancement, topic:buildsystem, cherrypick:4.1, cherrypick:4.2

#1530 SCons: Remove old Python 2 compat code
  tools/ios.py
Labels: enhancement, topic:buildsystem, cherrypick:4.1, cherrypick:4.2

#1531 [3.x] SCons: Remove old Python 2 compat code
  SConstruct
Labels: enhancement, topic:buildsystem, cherrypick:3.5
