Repository godotengine/godot-cpp, pull requests merged in 2024-02, with the labels that each got.

#1384 Added newer Variant types to `typed_array.hpp`
  include/godot_cpp/core/type_info.hpp
  include/godot_cpp/variant/typed_array.hpp
Labels: bug, topic:gdextension

#1363 Fix object return value of builtin types' methods.
  binding_generator.py
  include/godot_cpp/core/builtin_ptrcall.hpp
Labels: bug, cherrypick:4.1, cherrypick:4.2

#1377 Allow GDExtensions to register virtual methods and call them on scripts (godot-cpp support)
  binding_generator.py
  gdextension/gdextension_interface.h
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/core/object.hpp
  include/godot_cpp/core/property_info.hpp
  include/godot_cpp/godot.hpp
  src/core/class_db.cpp
  src/godot.cpp
  test/project/example.gd
  test/project/main.gd
  test/project/main.tscn
  test/src/example.cpp
  test/src/example.h
Labels: enhancement, waiting for Godot

#1391 [SCons] Add support for custom build tools and platforms
  tools/godotcpp.py
Labels: enhancement, topic:buildsystem, cherrypick:4.1, cherrypick:4.2

#1367 Use latest doc version in issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: enhancement, topic:buildsystem

#1392 [SCons] Split `targets.py`, apply flags from tools
  tools/android.py
  tools/common_compiler_flags.py
  tools/godotcpp.py
  tools/ios.py
  tools/linux.py
  tools/macos.py
  tools/targets.py
  tools/web.py
  tools/windows.py
Labels: enhancement, topic:buildsystem, cherrypick:4.1, cherrypick:4.2
