Repository godotengine/godot-cpp, pull requests merged in 2024-08, with the labels that each got.

#1330 Add hot reload support to CMakeLists.txt
  CMakeLists.txt
Labels: cmake, topic:buildsystem, cherrypick:4.2

#1539 Make sure `_get` and `_set` dispatch up the class hierarchy
  include/godot_cpp/classes/wrapped.hpp
Labels: bug

#1543 Use GitHub admonition syntax for the warning in README
  README.md
Labels: enhancement

#1545 Removes warnings generated by GDCLASS usage
  include/godot_cpp/classes/wrapped.hpp
Labels: enhancement, topic:buildsystem, cherrypick:4.1, cherrypick:4.2

#1546 Fix missing type info for PackedVector4Array
  include/godot_cpp/core/method_ptrcall.hpp
  include/godot_cpp/core/type_info.hpp
  include/godot_cpp/variant/typed_array.hpp
  src/variant/variant.cpp
Labels: bug

#1528 Make generated code mostly style compliant
  binding_generator.py
Labels: enhancement, topic:buildsystem, cherrypick:4.1, cherrypick:4.2

#1555 Avoid hardcoded type conversion for metadata
  binding_generator.py
Labels: bug, topic:gdextension, cherrypick:4.1, cherrypick:4.2, cherrypick:4.3

#1557 Fix incorrect generation of some C++ operators
  binding_generator.py
Labels: bug, cherrypick:4.1, cherrypick:4.2, cherrypick:4.3

#1554 Correct type for `char16` and `char32` meta
  binding_generator.py
Labels: enhancement, topic:gdextension, cherrypick:4.3

#1558 Fix missing MAKE_TYPED_ARRAY_INFO for Packed*Arrays
  include/godot_cpp/core/type_info.hpp
  test/src/example.cpp
  test/src/example.h
Labels: bug, cherrypick:4.3

#1559 [4.2] Fix missing MAKE_TYPED_ARRAY_INFO for Packed*Arrays
  include/godot_cpp/core/type_info.hpp
  test/src/example.cpp
  test/src/example.h
Labels: bug, cherrypick:4.1

#1560 [Web/SCons] Use CCFLAGS for SIDE_MODULE option
  tools/web.py
Labels: enhancement, platform:web, topic:buildsystem, cherrypick:4.1, cherrypick:4.2, cherrypick:4.3

#1561 Fix GCC 14 -Wtemplate-id-cdtor warning
  include/godot_cpp/templates/safe_refcount.hpp
Labels: bug, topic:buildsystem, cherrypick:4.1, cherrypick:4.2, cherrypick:4.3

#1520 Add a test to ensure that library path is absolute
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
Labels: enhancement, topic:buildsystem, cherrypick:4.2, cherrypick:4.3
