Repository godotengine/godot-cpp, pull requests merged in 2025-04, with the labels that each got.

#1753 Fix stack smashing when Godot methods return `char32_t`, `char16_t` or `wchar_t`
  include/godot_cpp/core/engine_ptrcall.hpp
  include/godot_cpp/core/method_ptrcall.hpp
Labels: bug, crash, cherrypick:4.3, cherrypick:4.4

#1742 Add missing Projection constructor with 16 `real_t` values
  include/godot_cpp/variant/projection.hpp
  src/variant/projection.cpp
Labels: bug, cherrypick:4.4

#1754 Add method_ptrcall header include to type_info to fix compiler errors
  include/godot_cpp/core/type_info.hpp
Labels: bug, cherrypick:4.4

#1717 Add support for range based loops for Array
  binding_generator.py
  include/godot_cpp/variant/variant.hpp
  src/variant/packed_arrays.cpp
Labels: enhancement, cherrypick:4.4

#1726 Update CI with new CMake builds.
  .github/actions/setup-godot-cpp/action.yml
  .github/workflows/ci-cmake.yml
  .github/workflows/ci-scons.yml
  .github/workflows/runner.yml
  .github/workflows/static_checks.yml
  CMakeLists.txt
  cmake/godotcpp.cmake
  cmake/ios.toolchain.cmake
Labels: topic:buildsystem, cherrypick:4.4

#1760 Update test project to Godot 4.4
  test/project/example.gd.uid
  test/project/example.gdextension.uid
  test/project/main.gd.uid
  test/project/main.tscn
  test/project/project.godot
  test/project/test_base.gd.uid
Labels: enhancement, cherrypick:4.4

#1750 Typed dictionary initializer support
  include/godot_cpp/classes/ref.hpp
  include/godot_cpp/templates/pair.hpp
  include/godot_cpp/variant/typed_dictionary.hpp
Labels: enhancement, cherrypick:4.4

#1716 Add support for `initializer_list` to Array and TypedArray
  binding_generator.py
  include/godot_cpp/variant/typed_array.hpp
  include/godot_cpp/variant/variant.hpp
Labels: enhancement, cherrypick:4.4

#1767 Use Math::abs to avoid ambiguity with integer abs
  include/godot_cpp/variant/quaternion.hpp
Labels: bug, cherrypick:4.4

#1758 Sync defs
  include/godot_cpp/core/binder_common.hpp
  include/godot_cpp/core/defs.hpp
  include/godot_cpp/core/math.compat.inc
  include/godot_cpp/core/math.hpp
  include/godot_cpp/core/math_defs.hpp
  include/godot_cpp/core/memory.hpp
  include/godot_cpp/variant/plane.hpp
  include/godot_cpp/variant/vector3.hpp
  src/variant/plane.cpp
  tools/godotcpp.py
Labels: enhancement, cherrypick:4.4

#1763 Fix TypedDictionary binding generation
  binding_generator.py
Labels: bug, cherrypick:4.4

#1768 CI: bump of mozilla-sccache action to 0.0.9
  .github/workflows/ci-cmake.yml
Labels: bug, topic:buildsystem, cherrypick:4.4

#1770 Use Math::abs to avoid ambiguity with integer abs
  src/variant/basis.cpp
Labels: bug, cherrypick:4.4

#1756 SCons: Add `CPPEXTPATH` for external includes
  tools/godotcpp.py
  tools/windows.py
Labels: enhancement, topic:buildsystem, cherrypick:4.3, cherrypick:4.4

#1743 Register the classes used with the Godot editor
  gdextension/gdextension_interface.h
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/godot.hpp
  src/core/class_db.cpp
  src/godot.cpp
Labels: enhancement

#1776 Fix classes without `_to_string()` always returning `"[Wrapped:0]"`
  binding_generator.py
  include/godot_cpp/classes/wrapped.hpp
  test/project/main.gd
Labels: bug, cherrypick:4.3, cherrypick:4.4

#1774 Fix ClassDB iterators making unintended copies
  src/core/class_db.cpp
Labels: bug, cherrypick:4.3, cherrypick:4.4
