Repository godotengine/godot-cpp, pull requests merged in 2025-07, with the labels that each got.

#1803 Cherry-picks for the godot-cpp 4.3 branch - 5th batch
  .github/workflows/ci.yml
  README.md
  binding_generator.py
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/engine_ptrcall.hpp
  include/godot_cpp/core/method_bind.hpp
  include/godot_cpp/core/method_ptrcall.hpp
  include/godot_cpp/variant/projection.hpp
  src/core/class_db.cpp
  src/core/method_bind.cpp
  src/variant/projection.cpp
  test/project/main.gd
  tools/android.py
  tools/godotcpp.py
  tools/ios.py
  tools/windows.py
Labels: bug, enhancement

#1669 Add SCons variant_dir support
  SConstruct
  tools/godotcpp.py
Labels: enhancement, topic:buildsystem, cherrypick:4.3, cherrypick:4.4

#1817 Reintroduce Math_INF and Math_NAN defines
  include/godot_cpp/core/math_defs.hpp
Labels: bug, cherrypick:4.4

#1818 Test that internal classes work as expected
  gdextension/gdextension_interface.h
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/godot.hpp
  src/godot.cpp
  test/project/main.gd
  test/src/example.cpp
  test/src/example.h
  test/src/register_types.cpp
Labels: bug
