Repository godotengine/godot-cpp, pull requests merged in 2025-06, with the labels that each got.

#1757 CI: Various version bumps; sync with main repo
  .clang-format
  .editorconfig
  .pre-commit-config.yaml
  SConstruct
  binding_generator.py
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/method_bind.hpp
  include/godot_cpp/variant/callable_method_pointer.hpp
  include/godot_cpp/variant/char_string.hpp
  include/godot_cpp/variant/variant.hpp
  pyproject.toml
  test/src/example.cpp
  test/src/example.h
Labels: enhancement, topic:buildsystem, cherrypick:4.3, cherrypick:4.4

#1777 CI: Ensure utf-8 support on Windows GHA
  .github/workflows/ci-scons.yml
Labels: bug, enhancement, topic:buildsystem, cherrypick:4.3, cherrypick:4.4

#1771 Fix array constructor crash
  include/godot_cpp/variant/variant.hpp
Labels: bug, cherrypick:4.4

#1779 Make ndk version configurable as a command-like argument.
  tools/android.py
Labels: enhancement, topic:buildsystem, cherrypick:4.3, cherrypick:4.4

#1790 Fix URL to gdextension cpp example in the official docs
  README.md
Labels: documentation, cherrypick:4.3, cherrypick:4.4

#1773 Clean up the MethodBind class
  include/godot_cpp/core/method_bind.hpp
  src/core/method_bind.cpp
Labels: enhancement, cherrypick:4.3, cherrypick:4.4

#1794 Fix binding generation for `TypedArray`/`TypedDictionary` with refcounted elements.
  binding_generator.py
Labels: bug, enhancement, topic:buildsystem, cherrypick:4.4

#1796 [GitHub CI] Fix source detection, added missing include .hpp and .inc to detection rules.
  .github/workflows/runner.yml
Labels: bug, topic:buildsystem, cherrypick:4.3, cherrypick:4.4

#1799 Disable double precisions builds in CI for now
  .github/workflows/ci-cmake.yml
  .github/workflows/ci-scons.yml
Labels: bug, topic:buildsystem
