Repository godotengine/godot-cpp, pull requests merged in 2025-01, with the labels that each got.

#1670 CMake: Support for using build_profile.json
  cmake/godotcpp.cmake
  cmake/python_callouts.cmake
Labels: enhancement, cmake, topic:buildsystem

#1682 CMake: Support for XML documentation
  cmake/python_callouts.cmake
  doc_source_generator.py
  test/CMakeLists.txt
  tools/godotcpp.py
Labels: enhancement, cmake, topic:buildsystem

#1686 Update README.md with new pre-commit instructions
  README.md
Labels: documentation, cherrypick:4.2, cherrypick:4.3

#1687 Fix buffer overrun with enums pointers cast to int64_t* when enum is only 32-bit
  binding_generator.py
Labels: bug, cherrypick:4.2, cherrypick:4.3

#1628 fix typed_dictionary compile-time regression
  include/godot_cpp/core/type_info.hpp
  include/godot_cpp/variant/typed_dictionary.hpp
  test/src/example.cpp
  test/src/example.h
Labels: bug

#1694 Cherry-picks for the godot-cpp 4.2 branch - 9th batch
  .github/actions/godot-cache-restore/action.yml
  .github/actions/godot-cache-save/action.yml
  .github/actions/setup-godot-cpp/action.yml
  .github/workflows/ci.yml
  .github/workflows/runner.yml
  .github/workflows/static_checks.yml
  README.md
  binding_generator.py
  build_profile.py
  include/godot_cpp/classes/ref.hpp
  include/godot_cpp/core/defs.hpp
  include/godot_cpp/variant/quaternion.hpp
  include/godot_cpp/variant/variant.hpp
  include/godot_cpp/variant/vector4.hpp
  misc/scripts/check_get_file_list.py
  src/variant/quaternion.cpp
  test/build_profile.json
  tools/android.py
  tools/common_compiler_flags.py
  tools/godotcpp.py
  tools/ios.py
  tools/linux.py
  tools/macos.py
  tools/web.py
  tools/windows.py
Labels: bug, enhancement

#1695 Cherry-picks for the godot-cpp 4.3 branch - 3rd batch
  .github/actions/godot-cache-restore/action.yml
  .github/actions/godot-cache-save/action.yml
  .github/actions/setup-godot-cpp/action.yml
  .github/workflows/ci.yml
  .github/workflows/runner.yml
  .github/workflows/static_checks.yml
  README.md
  binding_generator.py
  build_profile.py
  include/godot_cpp/classes/ref.hpp
  include/godot_cpp/classes/wrapped.hpp
  include/godot_cpp/core/class_db.hpp
  include/godot_cpp/core/defs.hpp
  include/godot_cpp/core/print_string.hpp
  include/godot_cpp/variant/quaternion.hpp
  include/godot_cpp/variant/variant.hpp
  include/godot_cpp/variant/vector4.hpp
  misc/scripts/check_get_file_list.py
  src/classes/wrapped.cpp
  src/core/class_db.cpp
  src/core/print_string.cpp
  src/variant/quaternion.cpp
  test/build_profile.json
  tools/android.py
  tools/common_compiler_flags.py
  tools/godotcpp.py
  tools/ios.py
  tools/linux.py
  tools/macos.py
  tools/web.py
  tools/windows.py
Labels: bug, enhancement

#1691 CMake: Fix #1690 - DEBUG_FEATURES generator expression
  cmake/godotcpp.cmake
Labels: cmake
